# -*- coding: utf-8 -*-
"""Job 42 CV-rejection feedback emails — BATCH 04 (10 candidates, manifest batch_04.json).
Layout: templates/cv_rejection_template_locked.html (v8, LOCKED — placeholders only).
Rules: 800+ words, CV-only evidence (no fabricated interaction), no em dashes, we-voice,
role-fit framing, no intent inference, candidate-initiated reapplication, no abstractions.
Outputs: output/job42/rejection_emails/<app_id>_<name>.html
DRAFTS ONLY — nothing in this script sends email.
"""
import os, re

TEMPLATE = open(r"c:\Agent Coco\templates\cv_rejection_template_locked.html", encoding="utf-8").read()
OUT = r"c:\Agent Coco\output\job42\rejection_emails"
os.makedirs(OUT, exist_ok=True)

P = ('<p style="margin:0 0 18px 0;text-align:justify;font-family:Georgia,serif;'
     'font-size:15px;line-height:1.8;">{}</p>')

def paras(*texts):
    return "".join(P.format(t) for t in texts)

EMAILS = [
{
 "app_id": 3917, "first": "Humaira", "name": "Humaira Nadeem", "email": "humairanadeemhn84@gmail.com",
 "subject": "From a 2004 classroom to a principal's office, read with care",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Your application carries more than twenty years of work in classrooms and school offices, including a chapter spent with us, and a record like that deserves an honest, specific account of what we appreciated and where the decision came from, not a form letter.",
   "We write to every applicant this way for a simple reason: a decision that affects someone's next months should arrive with its reasoning attached. Everything below comes from the written application you submitted, and we hope it proves useful well beyond this one process."),
 "s1": paras(
   "The first thing that stood out was the length and steadiness of the arc. It begins at Noor Academy in 2004, teaching English, Science and Math in Rawalpindi, and it arrives in 2025 at the principal's office of Allied School in Banigala, by way of Montessori classrooms at Discovery School System, a level incharge post across Grades 1 to 4 at The Smart School, and a multi-hat tenure at Unity International School. Careers that climb from classroom teacher to principal inside the same community, one widened responsibility at a time, are built on years of simply showing up well.",
   "Second, the width of the principal's chair as you describe it. Academic and administrative operations, teacher supervision and curriculum implementation, admissions and parent communication, financial and procurement processes, teacher training, co-curricular events, and facility safety and security. That is an entire institution held in one job description, and the Unity International years show the same pattern: educator, Tarbiyah focal person and trainer, administrative relations, front desk operations, inventory, discipline and E-School management, all carried at once.",
   "Third, and we note this warmly: part of your record was written with us. Curriculum-aligned digital and printable content, collaboration with education specialists to refine instructional material, and professional editing and review of educational content. We recognize the craft in that work, and it made your application a genuinely careful read for us.",
   "The subject range matters too: Math, Urdu, social studies and Islamiat across primary and middle grades at The Smart School, values-based education implemented alongside academic goals, and skill-based early-years learning at Discovery School System. Leaders who have taught across that many subjects and stages tend to judge curriculum decisions from the classroom floor rather than from the office window, and your application reads exactly that way.",
   "And the Master of Human Resource Management still in progress at Allama Iqbal Open University, held alongside a full principal's workload, tells us the learning has not stopped in year twenty of the career."),
 "s2": paras(
   "Here is where the decision came from. This seat is not a school-leadership role. It is the hands-on execution engine of our growth function, a second-in-command reporting into our Head of Growth: its counterparties are provincial education departments, government officials, and development and donor organizations; its craft is winning new institutional partnerships; and its daily discipline is a commercially run relationship record in a CRM, with forty to sixty percent domestic travel to partner sites across Pakistan.",
   "Your application documents deep authority inside a school: curriculum, staff, parents, operations, safety. What we could not find in the written application was the other motion this role requires: acquiring external partners, carrying growth or revenue targets, or engaging government and donor counterparties as a partnership builder rather than as an academic leader. The role required proven mileage on that commercial terrain, and with one seat to fill we went with evidence we could see there. That is a statement about the shape of this particular seat, not about the school leader visible on the page."),
 "s3": paras(
   "Our suggestion is to aim where the record is already strong. School leadership, academic operations, teacher training and educational content development are all arenas where your application argues for itself, and the content, editing and review work you did with us sits close to roles that education organizations, including ours, hire for repeatedly. If institution-facing work still pulls at you, the bridge from principal to partnerships usually runs through program delivery roles in education organizations, where school-side credibility is an asset from the first day. The diploma in computer engineering, the E-School management experience and the digital learning tools you list also deserve a more prominent place on the page, because education employers increasingly staff for exactly that blend of classroom authority and digital fluency.",
   "One practical note offered in good faith: the CV lists the Taleemabad chapter without dates, while every other role carries them; adding the period would let any reader place that work correctly in the arc. Our openings live at taleemabad.com, and content, pedagogy and school-facing roles do open as we grow; if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "Twenty one years separate the teacher at Noor Academy from the principal at Allied School, and much of that climb happened in front of the same Banigala community. Institutions keep trusting people like that for a reason."
},
{
 "app_id": 3918, "first": "Amara", "name": "Amara Naqui", "email": "amara.naqui4@gmail.com",
 "subject": "From crop genomics to classroom programs, one instinct",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Your application moves between bioinformatics research and education program coordination with unusual range, and it deserves an honest, specific account of what we appreciated and where the decision came from rather than a template.",
   "We write to every applicant this way because a decision that affects someone's next months should arrive with its reasoning attached. Everything below is grounded in the written application you submitted, and nothing else."),
 "s1": paras(
   "What stood out first was the scope of the coordination work at American Lycetuff. Three named projects: Early Childhood Education with the Ministry of Federal Education and Professional Training and ALS, the Education Vouchers Program, and the strengthening of social emotional learning in schools through scripted lesson plans and digital content. Across them you describe coordinating academic and administrative work across multiple campuses, running online and onsite teacher training workshops, preparing result tabulation sheets for the ECE and voucher programs, monitoring campuses through regular visits, and keeping reports, records and compliance documents moving on time. That is a real operational spine, documented project by project.",
   "Second, the academic record underneath it. A Bachelor of Science in Bioinformatics at a 3.83 CGPA, a Master of Science at 3.63 with a thesis applying artificial intelligence to crop efficiency prediction, and earlier laboratory work in DNA profiling and questioned-document analysis at the National Forensic Science Agency. Analytical rigor of that kind does not switch off when the subject matter changes.",
   "Third, the classroom years. STEM, Biology and Chemistry at Nobel STEM School alongside admissions, timetables and events; Science and Social Studies at Toddler House and The King's; STEM workshops with Robotmea. You have taught in the very classrooms that education programs are designed for, which is rarer among program coordinators than it should be, and it shows in how concretely the coordination work is described.",
   "Fourth, the width of the operational remit. The application lists hiring, interviewing, onboarding and termination processes managed, recruitment advertisements prepared and published, academic and administrative guidelines, policies and standard operating procedures developed and circulated, and institutional data organized on shared drives and digital platforms. Add the earlier content writing for a UAE-based company and an EdTech internship at Jaamiah.com, and the record shows someone repeatedly trusted with the unglamorous scaffolding that keeps institutions running."),
 "s2": paras(
   "Here is where the decision came from. The growth in this seat happens outside the organization: winning new partnerships with provincial education departments, government bodies and development and donor organizations, carrying acquisition targets, and running that effort through disciplined CRM records with forty to sixty percent domestic travel. It is a commercial, externally facing motion, scoped for someone roughly four to six years into that specific kind of work, reporting into our Head of Growth as a hands-on second.",
   "Your application documents the complementary motion: implementing and monitoring programs inside a school network once the programs exist. Coordination, training, tabulation, compliance and communication between head office and campuses are delivery craft, and the application shows them clearly. What we could not find in the written application was the acquisition side: partnerships you personally sourced and closed with external institutions, growth or revenue targets carried, or government and donor counterparties engaged as a deal owner rather than as a program coordinator. The role required demonstrated mileage there, and with one seat to fill we went with evidence we could see on that terrain. That is a judgment about fit with this seat, not about the professional on the page."),
 "s3": paras(
   "Our suggestion is to lean into the lane your record already argues for: program coordination, monitoring and evaluation, and program officer roles in donor-funded education programs. The three portfolios you have touched, early childhood education, education vouchers and social emotional learning, are exactly the portfolios that development organizations in Pakistan staff continuously, and your data instincts, from thesis-level analysis to tabulation sheets, are a genuine differentiator in that market. Name the outcomes with numbers wherever you can: campuses covered, teachers trained, reporting cycles held; the application currently describes duties more than results, and the results deserve the space. The Canva and documentation skills you list would also let you carry program communications alongside coordination, which is a genuine plus in donor-facing teams.",
   "Our openings live at taleemabad.com, and program and coordination roles do open as we grow; if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "A thesis on predicting crop efficiency with artificial intelligence and a result tabulation sheet for an early childhood program are the same habit wearing different clothes: making systems measurable. Keep that habit; it travels everywhere."
},
{
 "app_id": 3920, "first": "Hassaan", "name": "Hassaan Abdullah", "email": "hafizhassaan14@gmail.com",
 "subject": "Ten thousand dollars in month one, and the arena question",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Your application is short, but it is dense with closed deals and named outcomes, so we want to return that specificity in kind: an honest account of what we appreciated and exactly where the decision came from.",
   "We write to every applicant this way because a decision that affects someone's next months should arrive with its reasoning attached. Everything below comes from the written application alone."),
 "s1": paras(
   "The first thing that stood out was the pace of commercial results. Ten thousand dollars plus in brand partnership deals identified, negotiated and closed within the first month of the engagement, for a creator whose audience exceeds 385,000 followers. Closing within thirty days of arrival, in someone else's name and to someone else's brand standards, is harder than closing for yourself, and the application states it plainly with the number attached, alongside end-to-end campaign execution held to brand guidelines and timelines.",
   "Second, the trust gradient across the record. For a global creator with more than two million followers you ran the digital ecosystem end to end: Instagram, email and Patreon operations, community pages and membership tiers, international coordination, and sensitive business and personal data handled with discretion. Operators who can be handed an inbox, a calendar and a revenue platform simultaneously, and keep all three clean, are rarer than the job titles suggest.",
   "Third, the outreach muscle. Supporting the founder of Muslim Tech Fest, you carried sponsor and partner outreach, sat as the bridge between the founder and external stakeholders, and produced market research on the Muslim tech space to support decisions. Add the return-on-investment and engagement reporting you built for brand partners from campaign data, and a consistent shape emerges from the whole application: you find the counterparty, close the loop, and write the numbers down.",
   "There is also a quieter strength running across all three engagements: process. Internal communication and administrative workflows streamlined so the creator could stay on content while you carried the backend logistics; campaign performance tracked in spreadsheets and reported as return on investment and engagement to brand partners; complex calendars and high-priority correspondence handled with stated attention to detail. Partnership work runs on exactly this hygiene, and the application demonstrates it in each chapter rather than claiming it once in a summary line."),
 "s2": paras(
   "Here is where the decision came from. Growth in this seat is a different arena on two axes. Its counterparties are provincial education departments, government officials and development and donor organizations in Pakistan; its motion is field acquisition with forty to sixty percent domestic travel from an Islamabad base, run through disciplined CRM records; and it is scoped for someone roughly four to six years into exactly that kind of institutional work, reporting into our Head of Growth as a hands-on second.",
   "The record in your application is real but differently shaped on both axes. The partnership work is remote and creator-economy in nature, brands and sponsors engaged from behind a screen, and the dated roles span roughly 2024 to 2025, a shorter runway than this seat is scoped for. What we could not find in the written application was in-person institutional selling, public-sector or education-sector counterparties, or a multi-year record of carrying acquisition targets. The role required proven mileage on that specific terrain, and with one seat to fill we went with the evidence we could see there. None of that subtracts from what the record already shows."),
 "s3": paras(
   "Our suggestion is to protect the closing instinct and lengthen its record. The creator-partnerships market rewards exactly what you document, and each additional year of named, numbered deals compounds; keep publishing figures the way the current application does. If institutional work draws you, one deliberate step into a Pakistan-based organization that sells to schools, companies or public bodies would put face-to-face acquisition mileage next to the remote record, and the combination reads far stronger to hiring teams in our sector than either alone. A dated line for the BS in Computer Science would also help any reader place the arc of the career, and a short outcomes summary at the top would let a reader with thirty seconds reach the ten thousand dollar figure in the first five.",
   "Our openings live at taleemabad.com, and earlier-stage growth roles do open as we grow; if a matched role opens, we would welcome a fresh application from you."),
 "ps": "Closing ten thousand dollars of partnerships in a first month, for someone else's brand, is a line most applications cannot print. You printed it with the number attached, and that habit of proof will keep serving you."
},
{
 "app_id": 3922, "first": "Ahtesham", "name": "Ahtesham Younas", "email": "shamiminhas2@gmail.com",
 "subject": "Three hundred events, sixty companies, one campus",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. An application listing more than three hundred organized events and a stack of institutional roles deserves specificity in return, so here is an honest account of what we appreciated and exactly where the decision came from.",
   "We write to every applicant this way because a decision that affects someone's next months should arrive with its reasoning attached. Everything below is grounded in the written application you submitted."),
 "s1": paras(
   "The first thing that stood out was the sheer executional volume. More than three hundred events across categories as Manager of the Directorate of Student Affairs, External Linkages and the International Office, and one hundred forty plus in the earlier assistant manager chapter, including a grand auto show with media coverage, a Red Bull concert, a career fair that engaged over sixty companies and an alumni gathering that drew more than four hundred alumni. Event counts at that scale are logistics, sponsorship, security and stakeholder management run again and again until they become routine, and the application shows the machinery behind them: vendor selection, sponsor handling, national student trips planned and executed.",
   "Second, the institutional linkage work. Memoranda of understanding signed with international universities for student exchange, MOUs with corporations for internships and placements, and focal-person roles in national youth initiatives, the Young Peace and Development Corps under the Ministry of Planning and Development, and the Higher Education Commission's youth integration program. That is genuine exposure to how institutions formalize cooperation, earned early. The same chapters list membership of the purchase committee for transparent procurement, representation on the anti-drugs committee, coordination of cafeteria inspections and transport, and a career laboratory with an IELTS course for skill development, which together read as an administrator trusted with the campus itself, not just its calendar.",
   "Third, the service thread. A slums school project to widen access to basic education, a school renovation delivered in Islamabad, a computer laboratory built through charity funding, five hundred first-aid boxes delivered to the taxi community, blood donation and flood-relief drives. The application shows someone who points organizational skill at things that matter beyond the campus wall.",
   "And the sporting record deserves its own line: a Pakistan junior national hockey player with gold medals from the Pakistan Sports Board and the Federal Board. Competitive discipline of that kind tends to show up at work, and the event volume above suggests it already has."),
 "s2": paras(
   "Here is where the decision came from. This seat is the hands-on execution engine of our growth function, a second-in-command reporting into our Head of Growth, and its craft is commercial: winning new partnerships with provincial education departments, government bodies and development and donor organizations, carrying acquisition and revenue targets, running the effort through disciplined CRM records, and spending forty to sixty percent of the time traveling to partner sites across Pakistan.",
   "Your institutional relations were built inside a university's student affairs function, where counterparties largely come to the campus and success is measured in engagement rather than revenue. What we could not find in the written application was a partnership record with commercial targets attached: rupee values carried, acquisition quotas held, or education departments and donor organizations engaged as buying counterparties in the field. The role required demonstrated mileage on that terrain, and with one seat to fill we went with evidence we could see there. That is a fit judgment about this seat, not a ceiling on the record."),
 "s3": paras(
   "Our suggestion is to make the commercial layer of your record visible and then grow it deliberately. The sponsorships you secured, the twenty five stalls you filled for Islamabad Taste inside a month, the MOUs you signed: these all have values, counts and outcomes, and naming them in rupees and results would move the application from activity to impact. From there, external linkages and corporate relations roles in universities, or partnerships roles in education and youth-focused organizations, are the natural bridge from campus-facing work to revenue-carrying work, and your Ministry and Higher Education Commission focal-point exposure is a real asset on that path.",
   "Our openings live at taleemabad.com, and partnership and coordination roles do open as we grow; if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "A national junior hockey player who has organized three hundred events is describing one habit twice: preparation repeated until excellence looks ordinary. That habit is documented all over your application."
},
{
 "app_id": 3923, "first": "Zahid", "name": "Zahid sarohi", "email": "sarohizahid@gmail.com",
 "subject": "Seventeen percent more ROI, and two structural facts",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. In your case the decision rests on two structural facts about this seat rather than on the quality of the marketing record, and you deserve to hear both plainly, alongside what we genuinely appreciated in the application.",
   "We write to every applicant this way because a decision that affects someone's next months should arrive with its reasoning attached. Everything below comes from the written application you submitted."),
 "s1": paras(
   "The current chapter is the strongest. As Head of Marketing at Roots IVY College of Management Sciences you document a seventeen percent improvement in campaign return on investment through market research and analytics, a fifteen percent increase in student engagement and enrollment from multi-channel campaigns spanning social media, email, content and community outreach, and brand development that strengthened the institution's standing in the education sector. Enrollment growth is the revenue line of an education institution, and you own it with numbers attached.",
   "Second, the team and stakeholder dimension. You describe managing and mentoring a team of marketing professionals while aligning campaigns with academic departments, admissions teams and external partners, so the marketing engine and the institution pull in one direction. Mid-career marketers who can hold both the dashboard and the academic calendar are not common, and the application shows the alignment work explicitly rather than assuming it.",
   "Third, the foundation. A BS in Software Engineering from COMSATS underneath a search, social, pay-per-click and analytics stack, Google and Coursera certifications, an SEO team lead chapter at All Star Technology, and independent client projects run since 2021. The engineering degree explains the pattern across the record: marketing treated as a measurable system rather than a creative gamble.",
   "The run-up chapters add depth to the current title. A digital marketing specialist post at Progency Marketing, a manager chapter serving ICE Pakistan and Oxbridge, and independent projects at MCR Marketing and Nafay Marketing running complete campaigns including pay-per-click and Meta advertising. The certifications are linked in the application for direct verification rather than merely claimed, which is exactly the habit the rest of the record would predict."),
 "s2": paras(
   "Here are the two facts, stated without decoration. First, the arena. Growth in this seat is not demand generation through digital channels; it is field-built institutional partnerships with provincial education departments, government bodies and development and donor organizations, won in person across forty to sixty percent domestic travel and run through CRM discipline against partnership targets. Your growth craft, real as it is, operates on a different terrain: search engines, advertising platforms and social channels, with the student household as the counterparty rather than the education department. What we could not find in the written application was institutional, public-sector or donor-facing partnership work, and the role required proven mileage exactly there.",
   "Second, compensation. The expectation you shared sits well above what this role carries. That is structural to how the seat is graded, not a negotiating position, and we would rather state it cleanly than draw you into a process that ends at a figure far from the one you named. Both facts are about this seat as it exists today, not about the marketer described in the application."),
 "s3": paras(
   "Our suggestion is to keep compounding where the record is already strong. Head of digital growth and marketing leadership roles in universities, colleges and consumer education technology are the natural next seats, and the Roots IVY numbers, the seventeen percent ROI improvement and the fifteen percent enrollment lift, are precisely the figures those hiring committees read first; keep them at the top of the CV and add the rupee or headcount scale behind them so the percentages carry their full weight. The independent projects running since 2021 also deserve outcome numbers rather than task lists, because they show an ownership streak the employed chapters cannot. A marketing leadership application also gains from naming team size and budget scale; the current document describes the team and the channels but leaves both numbers out, and they belong on the page.",
   "Our openings live at taleemabad.com, and marketing-shaped roles do open as we grow; if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "A software engineer who chose marketing and then measured everything is not a detour; it is the reason a seventeen percent ROI improvement appears in your application as a fact rather than a feeling."
},
{
 "app_id": 3924, "first": "Ayesha", "name": "Ayesha Babar", "email": "ayeshababar2004@gmail.com",
 "subject": "The Eid campaign that carried half your sales",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. The decision in your case is mostly about timing and scope, not about the quality of what you have already built, and we want to walk through both honestly because the record deserves it.",
   "We write to every applicant this way because a decision that affects someone's next months should arrive with its reasoning attached. Everything below is drawn from the written application you submitted."),
 "s1": paras(
   "The first thing that stood out is that you built something real from zero. Glitter n' Glaze Events is run end to end in your own hands: campaign concept, audience targeting, post design briefs, vendor sourcing, inventory, packaging, logistics and after-sales support, with zero missed deliveries on record and, in the Eid campaign, a single campaign accounting for half of total business sales, the strongest performer to date. Founders learn what employees are usually shielded from: every unclosed loop lands on you, and the application reads like someone who already knows that. The full customer lifecycle sits in the same hands too, inquiries, order tracking and after-sales support run directly through social media, with customer satisfaction sustained across the run.",
   "Second, the coordination load at SAZ and Co. Four client accounts managed simultaneously at an assistant-coordinator level, each with its own records, content strategy, caption voice and posting schedule, plus influencer and partner relationships and performance analytics feeding content decisions, alongside scheduling, document management and Drive and Airtable record-keeping. Holding four brands apart in your head without dropping any of them is an organizational skill that scales.",
   "Third, the composure thread. Patient intake, scheduling and case-history work across hospital placements, including PIMS and CDA Hospital, put you in fast-moving, high-stakes rooms early, keeping accurate records while acting as the link between patients, doctors and administrative staff. That mix of people-facing steadiness and documentation discipline shows up in every chapter of the application.",
   "And underneath the work sits an education thread that fits it: a psychology degree at COMSATS approaching completion, A Levels in business studies and sociology before it, and clinical placements at two public hospitals. The application connects people-reading, record-keeping and commercial instinct in a way most early-career records never manage to document, and it does so with specifics rather than adjectives."),
 "s2": paras(
   "Here is where the decision came from, and it is mostly arithmetic. This seat is scoped for someone roughly four to six years into a growth career: it reports into our Head of Growth as a hands-on second, carries partnerships with provincial education departments, government bodies and development and donor organizations, runs on CRM discipline, and involves forty to sixty percent domestic travel across Pakistan.",
   "The written application documents a degree still in progress through 2026 and roughly two years of work across the founder, agency and hospital chapters. The role required a longer institutional record, particularly with government or education-sector counterparties, than any application at this career stage could reasonably contain. The written application also shows no CRM-run or institutional-selling record yet, which is no criticism at this stage; it is simply what four more years of deliberate work would build. The gap is the distance between one seat's scoping and one career's current mile marker, nothing more, and nothing in this letter should be read as a verdict on the trajectory itself."),
 "s3": paras(
   "Our suggestion is to be deliberate about the next two roles rather than hurrying toward seniority. A full-time growth, partnerships or coordination seat at a young company would compound the founder instincts you already have, and education or health organizations would value exactly the record you hold: campaign ownership with a revenue result, multi-account discipline and steadiness with people under pressure. Keep the business running if you can; a founder line with numbers attached will out-argue most internships on any future application. And keep quantifying the way you already do, because half of total sales from one campaign is the kind of line hiring teams remember. If growth work in education specifically attracts you, an entry role at an education organization would put the sector's rhythms, terms and counterparties into the record early, and that compounds faster than any title.",
   "Our openings live at taleemabad.com, and earlier-stage roles do open as we grow; if a matched role opens, we would welcome a fresh application from you."),
 "ps": "Zero missed deliveries while completing a psychology degree and holding four client accounts at once is not luck; it is systems. Whatever you build next will inherit them."
},
{
 "app_id": 3926, "first": "Asaad", "name": "ASAAD ANJUM", "email": "asaadanjum@gmail.com",
 "subject": "Churn seen 74 days out, and two structural facts",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. In your case the decision is structural rather than a judgment on capability, and a record like yours has earned a plain statement of the facts, alongside a precise account of what we appreciated.",
   "We write to every applicant this way because a decision that affects someone's next months should arrive with its reasoning attached. Everything below comes from the written application alone."),
 "s1": paras(
   "The current chapter reads like a clinic in commercial operations. A churn risk model that surfaces at-risk accounts sixty four percent earlier, moving detection from forty five to seventy four days so retention plays begin before renewal risk ever shows; three critical workflows rebuilt with AI tooling, eliminating ten to fifteen hours of weekly manual work; and a six-person account management team delivering back-to-back quota outperformance at one hundred one and one hundred fifteen percent on a three million dollar commercial book.",
   "Second, the coaching signature. A team member developed to seven hundred thirty six percent quota attainment, a company record at Motive, alongside faster new-hire ramp built through structured one-to-one coaching, cadence strategy and real-time KPI tracking. Managers who produce record-holders are documenting something rarer than personal quota.",
   "Third, the S&P Global arc. Annual recurring revenue grown forty percent, from six hundred seventy thousand to nine hundred thirty eight thousand dollars in eighteen months; two hundred thousand plus in net-new revenue generated through targeted outreach and live product demonstrations; renewal rates pushed to ninety eight percent on Salesforce hygiene and weekly reviews; ninety six percent retention and ninety nine percent satisfaction in the earlier associate chapter; and the firm's first AI customer-support chatbot shipped with product and engineering. The toolkit is named throughout, LinkedIn Sales Navigator, Salesloft cadences, Tableau and Power BI, and it produced adoption campaigns that lifted platform engagement forty percent and recovery work that saved ninety four percent of at-risk accounts, preserving over half a million dollars in recurring revenue.",
   "Even the earliest chapters carry numbers: twelve percent year-on-year growth and two vertical programs projected at fifteen million dollars plus at Allied Paint Industries, two million dollars in client tax savings and a thirty percent retention lift at The Wolf Group, and a 3.74 GPA with top-five-percent honors at Ithaca College underneath it all. Wherever the application is opened, the same operator appears, accountable to figures he publishes."),
 "s2": paras(
   "Here are the structural facts, stated cleanly. First, altitude: this seat is a hands-on second-in-command reporting into our Head of Growth, scoped for someone roughly four to six years into their career who carries the field work personally, writing the follow-ups and sitting in district waiting rooms. You operate today as a senior manager who builds teams, models and operating rhythms; the seat would use a fraction of the scope you have carried for years. Second, compensation: the expectation you shared sits well above what this role carries, and that is structural to how the seat is graded rather than a matter of negotiation.",
   "Beneath both sits an arena difference worth naming honestly. The record is North American software and financial-data commercial work, run largely through dashboards, CRM systems and remote motions, while this seat lives in Pakistani district offices, provincial education departments and donor organizations, at forty to sixty percent domestic travel. What we could not find in the written application was public-sector, education-sector or field-based partnership work in Pakistan, which is the specific terrain this seat exists to cover. Three separate reasons, and all three are about the seat, not the professional."),
 "s3": paras(
   "Our suggestion is to aim at the altitude and the price the record has earned. Commercial leadership seats in Pakistan-based technology companies selling into global markets are the direct continuation of the Motive and S&P chapters, and the churn-model and enablement work gives you a differentiated revenue-operations story few commercial leaders in this market can document. If the impact sector genuinely pulls you, enter it at director scale, where organizations buy exactly the forecasting, retention and team-building machinery you have already built, rather than through a mid-level field seat that would leave most of it idle. Donor-funded programs and international organizations in Islamabad also hire commercial operators at precisely your altitude for portfolio and partnerships leadership, and the S&P record travels well in those rooms.",
   "Our openings live at taleemabad.com, and senior roles do open as the organization grows; if a larger-scope role opens, we would welcome a fresh application from you."),
 "ps": "The number we kept rereading was not one of your own: seven hundred thirty six percent of quota, set by someone you coached. A record like that says as much about the coach as it does about the runner."
},
{
 "app_id": 3927, "first": "Shalar", "name": "Shalar ali", "email": "shalar.ali90@gmail.com",
 "subject": "Alliances worth 5.54 million rupees, and an arena question",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. A nine-year run through a military media office, a policy institute, a national incubation center and a coworking network deserves a precise explanation rather than a template, so here is an honest account of what we appreciated and exactly where the decision came from.",
   "We write to every applicant this way because a decision that affects someone's next months should arrive with its reasoning attached. Everything below is grounded in the written application you submitted."),
 "s1": paras(
   "The first thing that stood out was that the partnership work carries a number. Strategic alliances worth 5.54 million rupees secured with multinational technology partners across the AWS and Google Cloud ecosystems at Daftarkhwan, alongside principal-liaison duties for multi-stakeholder networks that included government bodies and international delegations, and compliance responsibility for national-level technology and economic forums. Partnership titles are common in applications; partnership rupee values are not, and yours is stated plainly.",
   "Second, the National Incubation Center chapter shows building, not just managing. A team of four professionals and sixteen interns supervised across structured programs, public-private partnership initiatives developed with ministries and industry leaders, innovation challenges and bootcamps designed and evaluated on project-cycle-management frameworks, and the Founders Coffee Club network scaled past fifteen hundred stakeholders. The named programs, Power to Her on women's workforce participation, Pak Green on climate, and a fintech hackathon with banking partners, show real range across gender, climate and financial inclusion. Designing a challenge and evaluating it against a framework are two different skills, and the application claims both with named programs a reader can check.",
   "Third, the communications spine underneath it all: communication strategies for national research programs and policy dialogues at the Pakistan Institute of Development Economics, and four years of national and international media campaigns at ISPR, with creative and analytics teams run under tight timelines. Partnership builders who can also carry the message themselves are rarer than either skill alone. The application also names the quieter disciplines: human resource planning and performance evaluation for operational teams, risk mitigation and compliance for national forums, advocacy campaigns for socioeconomic inclusion, and audience analytics used for risk communication. That is a full operating system for institutional work, not a single skill."),
 "s2": paras(
   "Here is where the decision came from, in two parts. First, the arena. This seat grows an education company: its counterparties are provincial education departments, school systems and education-focused development and donor organizations, and its motion is field acquisition at forty to sixty percent domestic travel, run through disciplined CRM records against revenue targets, as a hands-on second to our Head of Growth. Your alliances were built in the technology and innovation ecosystem, cloud vendors, startup networks and ministries around technology policy, and what we could not find in the written application was an education-sector counterparty or a quota-carrying, CRM-run acquisition record. The role required proven mileage on exactly that terrain, and with one seat to fill we went with evidence we could see there.",
   "Second, compensation. The expectation you shared sits well above what this role carries. That is structural to how the seat is graded rather than a matter of negotiation, and we would rather state it plainly than run a process toward a figure that could not close. Both parts are about this seat as it exists, not about the nine years on the page."),
 "s3": paras(
   "Our suggestion is to aim at partnership leadership seats in the technology, innovation and donor-program world where the record already argues for itself: incubation and accelerator networks, development programs built around the digital economy, and corporate alliance roles for cloud and platform vendors operating in Pakistan. One practical note offered in good faith: the profile paragraph of the CV closes by naming another organization's migration dialogues and regional project portfolios, which reads as a line carried over from a different application; wherever you apply next and profiles are read closely, that sentence is worth tailoring before submitting. It is a small thing, but a record as substantial as yours deserves packaging that keeps up with it; the alliance value, the network size and the team counts belong in the first five lines of the document.",
   "Our openings live at taleemabad.com, and partnership roles of different shapes do open as we grow; if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "A network of fifteen hundred stakeholders does not stay alive on charisma; it stays alive on maintenance. Scaling the Founders Coffee Club to that size is quiet proof of the less glamorous half of partnership work, which is the half that counts."
},
{
 "app_id": 3928, "first": "Rafae", "name": "Rafae", "email": "rafaemasood25@gmail.com",
 "subject": "Doubling ecommerce revenue, read against a field seat",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Your record in performance marketing is specific and quantified, so we owe you the same in return: an honest account of what we appreciated and exactly where the decision came from.",
   "We write to every applicant this way because a decision that affects someone's next months should arrive with its reasoning attached. Everything below comes from the written application alone."),
 "s1": paras(
   "The number that anchored our reading sits in the Hopscotch chapter: ecommerce revenue increased by more than one hundred percent, lifting the channel's contribution above thirty percent for the network. Behind it sits the full machinery: media planning, budgeting and buying across brand ecommerce initiatives, search engine marketing against monthly sales targets, inventory mapped to monthly ad spend to protect return, SMS and email lists worked through the database, and monthly performance reviews presented to directors through Google Analytics and Data Studio. That is a complete digital revenue operation held by one person.",
   "Second, the current craft at Game District. Multi-channel user acquisition across TikTok, AppLovin, Google and Mintegral, optimized for return on ad spend and positive returns on live games, with budgets managed across networks and campaigns aligned with product, creative and analytics teams. Gaming user acquisition is one of the least forgiving arenas in digital marketing, because the auction punishes every unexamined assumption in the account, and you have operated there for years.",
   "Third, the range behind it: community and campaign management for international brands including Huawei and Haier at Spark Pakistan, client-facing media planning and buying across Facebook, Google and YouTube, and a Master of Arts in International Economics and Business from Nankai University in Tianjin at eighty five percent, on top of an economics degree from Forman Christian College. The analytical spine of the record is visible in every chapter.",
   "Fourth, the professional hygiene around the craft. Certifications in Google advertising fundamentals, search and display, green and blue belt digital credentials, Mailchimp and advanced Excel in the toolkit, and, in the Spark Pakistan years, monthly performance reports produced per client, targets and KPIs achieved as the clients set them, and partnerships maintained with media agencies. The record shows the reporting rhythm, not just the results, and rhythm is what makes results repeat."),
 "s2": paras(
   "Here is where the decision came from. Growth in this seat is not media-buying growth. Its counterparties are provincial education departments, government bodies and development and donor organizations; its motion is in-person field acquisition across Pakistan at forty to sixty percent domestic travel from an Islamabad base; and its discipline is a CRM-run partnership record against institutional targets, as a hands-on second to our Head of Growth. The craft in your application, auctions, creatives, budgets and attribution, operates on a different terrain, and what we could not find in the written application was institutional, public-sector or donor-facing partnership work, or field-based selling of any kind. The application also places you in Lahore, while this seat is anchored in Islamabad with heavy travel beyond it. The role required proven mileage on its own terrain, and with one seat to fill we went with evidence we could see there. None of this is a comment on the quality of the craft; it is a statement about which craft this seat spends every week practicing."),
 "s3": paras(
   "Our suggestion is to keep compounding in the arena where the record is already strong. Senior performance and user-acquisition roles in gaming, ecommerce and consumer applications, including consumer education technology, are the natural next seats, and the Hopscotch revenue line beside the Game District network stack is a combination those hiring teams read fluently; keep both at the top of the CV with the numbers attached, and give the Game District outcomes the same numeric confidence as the Hopscotch line, because right now one chapter carries most of the arithmetic. If institution-facing growth genuinely draws you, the bridge is to pair the media craft with partnership exposure inside an organization that sells to institutions, so a future application can show both motions rather than one.",
   "Our openings live at taleemabad.com, and digital-growth roles do open as we grow; if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "Finishing a master's degree in Tianjin at eighty five percent and then mastering Mintegral auctions in Lahore is one skill wearing two coats: getting fluent, fast, in systems most people find opaque."
},
{
 "app_id": 3929, "first": "Usman", "name": "Usman Tariq", "email": "sh.usmantariq@gmail.com",
 "subject": "A five hundred percent November, and the terrain question",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. The application is full of numbers most records cannot show, so we want to hand the decision back with equal specificity: what we appreciated, and exactly where it came from.",
   "We write to every applicant this way because a decision that affects someone's next months should arrive with its reasoning attached. Everything below is grounded in the written application alone."),
 "s1": paras(
   "The first thing that stood out was the quota arc at Motive. One hundred percent in the third quarter, one hundred fifty in the fourth, one hundred sixteen to open 2026, and a five hundred percent November inside that run, generated by owning mid-market pipeline for fleets of fifty to one hundred seventy five vehicles through multi-channel outbound across email, LinkedIn and the phone. Sales development is a grind measured weekly, and the application shows the grind being won repeatedly, with Salesforce keeping the record honest and forecasting kept reliable. The application also describes partnering closely with account executives on deal progression, objection handling and conversion, which is the difference between a lead passer and a revenue teammate.",
   "Second, the MSMP chapter, the most unusual line in the application: more than 2.7 million dollars closed for a Quebec-based business using organic social channels alone, revenue scaled one hundred fifty percent in the first year, client retention lifted fifty percent, and a team built and trained around that engine while new locations opened on the strength of consistent client acquisition. Closing high-ticket clients without paid media is craft, not luck.",
   "Third, the Dynamics 360 years: worldwide client acquisition contributing a sixty five percent boost in business revenue, high-value negotiations closed at a consistent conversion rate, a team of sales professionals managed, and the company represented at international conferences across Europe where strategic partnerships were forged.",
   "And the record has an old-fashioned floor under it. At Idera Software you were promoted to lead the Pakistan collections division, lifted collections twenty percent in the first quarter of that leadership, and completed renewals as much as three months before their due dates. Reliability of that kind is the quiet engine behind every louder number that came after. The same chapter records top-tier rankings across multiple performance indicators and hands-on years with enterprise tools from Salesforce and Helpspot to Great Plains, and the marketing degree at COMSATS, completed while the early career was already running, explains the pattern of working systems hard from the start."),
 "s2": paras(
   "Here is where the decision came from. Growth in this seat happens face to face, in Pakistan, with institutions. Its counterparties are provincial education departments, government officials and development and donor organizations; its rhythm is forty to sixty percent domestic travel to partner sites; and its craft is long-cycle institutional partnership building as a hands-on second to our Head of Growth, rather than high-velocity outbound.",
   "The selling in your application is real and quantified, but it is aimed at North American fleets, worldwide clients and Quebec gym members, worked remotely through email, LinkedIn and the phone. What we could not find in the written application was a public-sector, education-sector or donor counterparty, or a field-based acquisition motion inside Pakistan. The role required proven mileage on that specific terrain, and with one seat to fill we went with evidence we could see there. That is a statement about arenas, not about the seller."),
 "s3": paras(
   "Our suggestion is twofold. First, the outbound engine you have built is at its most valuable exactly where you are pointing it: Pakistan-based teams selling into North America and Europe pay a premium for documented quota arcs, and yours is current, verifiable and steep; protect it and let it compound. Second, if institutional work in Pakistan genuinely draws you, one deliberate chapter selling to public bodies, schools or large domestic enterprises, even within your current employer's ecosystem, would put in-country institutional evidence next to the remote record, and the combination would read very differently to hiring teams in our sector.",
   "Our openings live at taleemabad.com, and growth roles of different shapes do open as we grow; if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "A five hundred percent month is the loud number, but the one we kept returning to is quieter: renewals completed three months before their due dates. The second habit is why the first keeps happening."
},
]  # SPLIT_MARKER_A

built = []
for e in EMAILS:
    html = TEMPLATE
    html = html.split("<!DOCTYPE")[1]
    html = "<!DOCTYPE" + html  # drop the top comment block
    html = html.split("<!--\nCV REJECTION RULES")[0]  # drop trailing rules comment
    html = html.replace("[SUBJECT_LINE]", e["subject"])
    html = html.replace("[ROLE]", e["role"])
    html = html.replace("[CANDIDATE_FIRST_NAME]", e["first"])
    html = re.sub(r'<p style="margin:0 0 18px 0;[^"]*">\[OPENING_PARAGRAPH:[^\]]*\]</p>', e["opening"], html)
    html = re.sub(r'<p style="margin:0 0 18px 0;[^"]*">\[SECTION_1_CONTENT:[^\]]*\]</p>', e["s1"], html)
    html = re.sub(r'<p style="margin:0 0 18px 0;[^"]*">\[SECTION_2_CONTENT:[^\]]*\]</p>', e["s2"], html)
    html = re.sub(r'<p style="margin:0 0 18px 0;[^"]*">\[SECTION_3_CONTENT:[^\]]*\]</p>', e["s3"], html)
    html = html.replace("[PS_CONTENT: one memorable, character-affirming line tied to a specific moment.]", e["ps"])
    html = re.sub(r'<!-- \[FEEDBACK_WIDGET\][^>]*-->', '<!-- FEEDBACK_WIDGET_HERE -->', html)
    assert "[" not in re.sub(r'<!--.*?-->', '', html, flags=re.S), f"unfilled placeholder in {e['name']}"
    path = os.path.join(OUT, f"{e['app_id']}_{re.sub(r'[^a-zA-Z0-9]', '_', e['name'])}.html")
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    words = len(re.sub(r'<[^>]+>', ' ', html).split())
    built.append((e["app_id"], e["name"], path, words))
    print(f"built {e['app_id']} {e['name']}: ~{words} words -> {path}")
