# -*- coding: utf-8 -*-
"""Job 42 CV-rejection feedback emails — BATCH 01 (10 candidates, manifest wave_batches/batch_01.json).
Layout: templates/cv_rejection_template_locked.html (v8, LOCKED — placeholders only).
Rules: 800+ words, CV-only evidence (no fabricated interaction), no em dashes, we-voice,
role-fit framing, no intent inference, candidate-initiated reapplication, no abstractions.
Outputs: output/job42/rejection_emails/<app_id>_<name>.html
DRAFTS ONLY — nothing in this script sends email.
"""
import io, os, re

TEMPLATE = open(r"c:\Agent Coco\templates\cv_rejection_template_locked.html", encoding="utf-8").read()
OUT = r"c:\Agent Coco\output\job42\rejection_emails"
os.makedirs(OUT, exist_ok=True)

P = ('<p style="margin:0 0 18px 0;text-align:justify;font-family:Georgia,serif;'
     'font-size:15px;line-height:1.8;">{}</p>')

def paras(*texts):
    return "".join(P.format(t) for t in texts)

EMAILS = [
{
 "app_id": 3874, "first": "Ersalan", "name": "Ersalan Falegh Ali Chowhan", "email": "faleghchowhan@gmail.com",
 "subject": "Five hundred Starbucks sites, and the question of arena",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. A decade of work went into the record you submitted, and it was read in full; the least it deserves in return is an honest, specific account of what stood out and exactly where the decision came from.",
   "We write to every applicant this way because a decision that touches someone's next months should carry its reasoning with it. Everything below is grounded in the written application alone, which is the only fair source at this stage, and we hope it proves useful well beyond this one process."),
 "s1": paras(
   "The Starbucks deployment is the chapter we kept returning to. Coordinating a multi-site technology rollout across five hundred plus Starbucks locations in the United States, holding cross-border stakeholder communication steady, automating the inventory and reporting layer to cut the order-to-deployment cycle time, and still landing the project on time and under budget, is delivery discipline of a kind most applications cannot show.",
   "The retention thread runs just as consistently. A twenty five percent increase in customer retention built on structured onboarding and lifecycle management, more than one hundred projects led across Salesforce customization, compliance and digital solutions at CrecenTech, and churn reduced at Cedar Financial through customized service packages, live training and documentation. The toolkit behind it, from HubSpot and Dynamics 365 to Totango, ChurnZero and Mixpanel, reads like someone who actually works these systems rather than lists them.",
   "And the early ledger holds up under weight. At United Bank Limited, the branch under your operations leadership was the highest revenue-generating location for two consecutive years, alongside two Top 3 finishes among customer service representatives in the North Region. At Dunia Finance in Dubai, the record shows three promotions in under a year on the back of exceeded targets. The pattern across twelve years is the same wherever the page is opened: the seat changes, the numbers move.",
   "The connective chapters fill the picture in rather than pad it. At Motive, product demos for inbound prospects ran at over ninety percent of monthly targets inside a four-month stint; at Square Nine, investment consulting across Gulf markets came with expo representation and acquisition channels built rather than inherited; and the MBA in accounting and finance sits on a 3.5 CGPA. None of these are headline chapters on their own, but together they document a professional who keeps producing wherever the desk happens to be."),
 "s2": paras(
   "Here is where the decision came from, stated as concretely as the strengths were. This seat is a hands-on growth-execution role inside Pakistan's education ecosystem, second chair to our Head of Growth and based in Islamabad. Its counterparties are provincial education departments, government institutions and development and donor organizations; its rhythm is forty to sixty percent domestic travel; and its core motion is winning new institutional partners in the field rather than growing accounts already won. The tools of that trade are proposals, district visits and procurement calendars more often than dashboards.",
   "The decade documented in the application is customer success, account stewardship and deployment coordination for commercial clients in the United States, the Gulf and Pakistan's banking sector. What we could not find in the written application was an education-sector or Pakistani public-sector counterparty anywhere in the file, or an acquisition motion in which a new institutional partnership was originated and closed rather than an existing relationship deepened. The professional summary also names the Gulf and Mena region, in writing, as the intended next arena, while this seat lives in district offices and school systems across Pakistan. With one seat to fill, we went with evidence on that exact terrain."),
 "s3": paras(
   "The craft transfers better than it may first appear. Retention discipline, deployment coordination and clean CRM hygiene are exactly what institutional partnership work runs on after a deal is signed; the missing layer is documented time with Pakistani public institutions. If the impact sector genuinely appeals, one deliberate chapter there, a public-sector deployment, an education or health program rollout, a donor-funded implementation, would connect craft we can already verify to the terrain organizations like ours hire against.",
   "One smaller note offered in good faith: the CV currently leads with a summary pointed at one region while its strongest verifiable chapters sit in Pakistan and the United States; aligning the stated destination with wherever the next application actually goes will let the document argue one clear thing from its first line. Our openings live at taleemabad.com; if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "Three promotions in under a year at Dunia Finance is a sentence most careers never get to write. Whatever arena comes next, that early gradient is documented, and it travels with you."
},
{
 "app_id": 3876, "first": "Shayan", "name": "Muhammad Shayan Abdullah", "email": "shayanpropak@gmail.com",
 "subject": "The quality bar you carried across five years",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Your application was read closely and in full, and because five years of steady, careful work sit behind it, we want to give you a specific account of what we appreciated and exactly where the decision came from.",
   "We write this way to every applicant for a simple reason: a no without reasons teaches nothing, and the person receiving it deserves better than a template. What follows is about your record and this particular seat, drawn from the written application alone, and nothing more general than that. It is longer than most rejection notes on purpose, because specificity is the only way a letter like this can be worth your reading time."),
 "s1": paras(
   "The quality thread in the record is genuinely consistent. At AHZ Associates the work moved beyond handling communication into setting its standard: reviewing counselling notes, case documentation and client correspondence for clarity, tone and accuracy, building benchmarking frameworks to calibrate human and template responses against one bar, and turning findings into documented best-practice recommendations. Quality assurance run as a system rather than a spot check is rarer than it sounds, and the application describes it precisely.",
   "The ownership chapter registered too. Running full branch operations for more than six months while supervising counselling teams is a real test of range for someone five years in, and the HubSpot depth beneath it, deal pipelines, automation workflows and reporting dashboards kept accurate enough to manage a team by, shows a professional who treats the CRM as the actual workplace rather than an afterthought. The British Council counselling certification alongside it shows the standard was formalized rather than improvised.",
   "The two years at All Star BPO round the picture out: high volumes of inbound and outbound communication handled against quality benchmarks, recurring issues traced to their failure modes and fed back into scripts and workflows, and targets for handling quality, resolution rate and satisfaction reached consistently rather than occasionally. It is unglamorous work done properly, and the application presents it without inflation, which we noted. Two years of that volume without the quality slipping is its own kind of endurance.",
   "And the through-line outside work says something the employment history alone cannot: volunteering with The Enlighteners since 2019 and with Jehad for Zero Thalassemia since 2023, sustained alongside full-time service roles. Commitment to causes held over years, not campaigns, is documented in this application rather than claimed."),
 "s2": paras(
   "Here is the honest center of the decision. This seat is an outbound growth-execution role: its daily motion is originating new institutional partnerships for education programs, with provincial education departments, government institutions and development and donor organizations as counterparties, forty to sixty percent domestic travel, and a personally carried revenue and partnership target. It is scoped for someone roughly four to six years into their career, but the specific four to six years it needs are years spent hunting. The CRM in this seat is not a register of arriving students; it is a live map of institutional deals moving toward signature, updated by the person carrying them.",
   "The five years documented in the application face inward: quality oversight, service delivery, counselling and record discipline for clients who had already arrived. What we could not find in the written application was an outbound acquisition motion, a revenue or partnership target owned end to end, or engagement with government or public-sector counterparties. The role required evidence of winning new institutional business; the record shows evidence of holding a standard once the door had already opened. Both matter. They are different jobs."),
 "s3": paras(
   "The education counselling chapter is a real bridge; it means the sector's language is already familiar. If partnership work is the direction, the most useful next step is documented outbound evidence inside the current role or the next one: institutional accounts opened with schools, universities or education providers, a target carried and reached, numbers a future reader can verify on the page. The branch-operations stretch already documents ownership held; pointing that ownership outward, toward new partners rather than arriving clients, is the move the record has not yet made on paper. Named accounts, dated wins and percentage-to-target lines are what turn a claim into a record, and five years of quality assurance work means the writing itself will already be clean.",
   "Our openings live at taleemabad.com, and roles closer to service quality, client operations and student-facing work do appear there as we grow; if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "Six years of volunteer work sustained alongside shift-based jobs is the detail we kept returning to. Records like that are built quietly, and they read louder than any summary paragraph."
},
{
 "app_id": 3877, "first": "Zain", "name": "Zain Qadir", "email": "zain_qadir@outlook.com",
 "subject": "A 500 million rupee budget, held to monthly closings",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Yours was one of the records where the decision needed the most care, because much of what it documents sits close to our world, so we want to lay the reasoning out plainly and completely.",
   "We write to every applicant this way because a decision should carry its reasons with it. Two of the facts below are structural, about the seat rather than about the professional described in the application, and we would rather name them cleanly than leave you guessing at them."),
 "s1": paras(
   "The Telenor chapter shows commercial machinery run with real discipline. A trade budget of five hundred million rupees owned through monthly financial and campaign closings, national distribution and trade strategy set from population, demographic and site data, and franchise churn cut by nine percent through a Power BI health model that turned monitoring into intervention for underperforming partners. The BVS Day Taakra campaign activating three thousand plus devices across regions, and the regular market visits behind retail and franchise branding, tell us the work happened in the field as well as in the deck.",
   "The Karandaaz year matters even more to us. Working relationships built with the Economic Affairs Division, SECP and the Pakistan Centre for Philanthropy, board governance and AGM obligations run to the letter of the law, and a ten million fund managed to support six hundred young female students through their education. That is documented time inside Pakistan's government and development ecosystem, at an organization sponsored by one of the world's most demanding funders.",
   "And the S&P Global chapters set the baseline early: five hundred plus cases handled at a 98.5 percent satisfaction rate, the DMS Product Specialist Award, trials measurably more likely to convert when your function was involved, and new hires mentored along the way. An MBA from NUST layered over a Dean's Honor List degree completes a record built step by deliberate step, with no chapter coasting. The Design Thinking certification at Telenor and the email campaigns designed in Salesloft at S&P bracket the record with the same signal at both ends: tools picked up as the work demanded them."),
 "s2": paras(
   "Here are the two structural facts, stated without decoration. First, compensation: the expectation you shared sits well above what this role carries. That is not a gap negotiation closes at the margins; it is how the seat is graded, and we would rather say so now than draw you into a process that ends at a number that does not work for you. We recognize the figure reflects a real market for this record; the mismatch is with this seat, not with the market.",
   "Second, the shape of the evidence. This seat's core motion is originating and closing institutional partnerships, with provincial education departments, government bodies and development and donor organizations as counterparties, carried personally through forty to sixty percent domestic travel and a hands-on CRM discipline. In the application, the government-facing chapter at Karandaaz was operations, governance and CSR coordination, and the commercial chapters at Telenor run through franchise and retail trade channels. What we could not find in the written application was the junction of the two: a partnership with a public institution originated, negotiated and closed as the core of the job itself. Close is the honest word for this record, and with one seat to fill, close was the distance that decided it."),
 "s3": paras(
   "The two halves of this record want to be joined, and the market has seats that join them. Partnership and business development roles at development-sector organizations, financial-inclusion programs and education or health companies selling to government value exactly this pairing: institutional fluency from the Karandaaz year, execution muscle from the Telenor budget. When the CV goes to such a seat, let the Karandaaz chapter state outcomes as concretely as the Telenor one does; the relationships with the Economic Affairs Division and SECP are named, but what they produced is not, and that missing line is the first thing a reader in our sector will look for. Two or three sentences quantifying what the CSR program changed, or what the fund's six hundred students went on to complete, would do more for the next reader than any skills list on the final page.",
   "Our openings live at taleemabad.com, and the organization is growing on several fronts; if a matched role opens, we would welcome a fresh application from you."),
 "ps": "A ten million fund carried for six hundred girls' education, inside a role titled operations analyst, is the detail we kept returning to. The education thread is already in your record; it did not need this application to put it there."
},
{
 "app_id": 3878, "first": "Asaad", "name": "Asaad Ali Akhunzada", "email": "asaad.shu@gmail.com",
 "subject": "From a team of four to a department, read closely",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Sixteen years of work across four countries deserve more than a form response, so here is an honest, specific account of what we appreciated and exactly where the decision came from.",
   "Nothing below is a verdict on the career the application describes. It is an account of fit between one record and one narrowly shaped seat, and we have tried to keep that distinction visible in every paragraph, because it is the distinction that matters. The short version is that the seat is shaped for a different career stage than the one this record has reached; the long version follows."),
 "s1": paras(
   "The building record is real and it is quantified. A marketing department grown from an initial team of four, with roles defined, hiring done and KPI frameworks installed; a managed client portfolio doubled within eighteen months at Moobila through retention processes and referral-based development; a forty percent plus uplift in traffic and conversions delivered across a twelve client portfolio; and vendor and tooling costs cut through renegotiation and platform consolidation. Outcomes with numbers attached, stated plainly.",
   "The modernization thread is just as visible. Company-wide adoption of generative AI tools led with usage guidelines and prompt libraries rather than enthusiasm alone; reporting automation that cut monthly reporting time by roughly thirty percent; a migration to ActiveCampaign that brought lead response time from forty eight hours to under four. Plenty of applications name AI; very few document the governance side of adopting it, and this one does.",
   "And the Pakistan chapters hold weight of their own. At Telecom Foundation Complex, a large-scale FTTH infrastructure tender carried end to end across technical, legal and commercial inputs, with go-to-market materials built for government and enterprise counterparties in IoT and smart cities. At CECOS University, enrolment-cycle campaigns, six plus outreach events, and an admissions app delivered through a managed vendor. The record touches both education and the public sector, and we read those pages closely before deciding.",
   "The earlier chapters complete the arc: an inventory tracking system introduced at Agile Marketing in Peshawar that cut product wastage by seventeen percent year on year, and franchise operations across RotiBoy outlets in Kuala Lumpur where order scheduling improvements reduced excess stock. Even the apprentice years produced measurable operational deltas, which is not common, and the CMI Level 7 diploma and Sheffield Hallam MBA formalized what the chapters were already showing."),
 "s2": paras(
   "Here are the two structural facts that decided it. First, compensation: the expectation you shared sits well above what this role carries, and that gap is graded into the seat rather than open to negotiation. Second, altitude: the recent arc runs through Head of Marketing and Marketing Director titles, with hiring, budgets and departments underneath it, while this seat is a second-chair, hands-on execution role reporting to our Head of Growth, scoped for someone roughly four to six years into their career and carrying a pipeline with their own hands every week. Placing a two-time head of function into that seat would spend years of accumulated scope on work the seat cannot use, and that arrangement serves neither the person nor the seat past the first quarter.",
   "There is a craft dimension too, and we state it carefully. The last six years of the record are digital and remote: channel marketing for portfolios in Australia, the United States and APAC, run from a screen with excellence. This seat's motion is in-person institutional acquisition across provincial education departments and development and donor organizations in Pakistan, with forty to sixty percent domestic travel. The tender and university chapters brush against that world, but what we could not find in the written application was a sustained record of field-based, government-facing partnership building as the job itself rather than as a supporting chapter."),
 "s3": paras(
   "Aim at the altitude the record has earned. Head-of-growth and head-of-marketing seats in edtech, e-learning and technology companies that sell to institutions would value this exact stack: demand generation with numbers attached, AI-era operating discipline, and enough tender literacy to sit comfortably inside a public-sector cycle. When applying there, move the Telecom Foundation and CECOS chapters up the page; in a sector like ours they are the most legible lines in the document, and they currently sit low.",
   "Our openings live at taleemabad.com, and seats of wider scope do open as the organization grows; if a larger-scope role opens, we would welcome a fresh application from you."),
 "ps": "One CV that holds a Kuala Lumpur franchise floor in 2009 and a prompt library in 2025 documents sixteen years of continuous re-tooling. That habit is the rarest line in the whole file."
},
{
 "app_id": 3880, "first": "Fawad", "name": "Syed Fawad", "email": "syedfawad95@gmail.com",
 "subject": "Twenty onboardings, QBRs, and a different motion",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Your application was read closely and in full, and because the record in it is careful and consistent, we want to return the same care: a specific account of what we appreciated and exactly where the decision came from.",
   "We write to every applicant this way because a decision that affects someone's plans should arrive with its reasoning attached. Everything below is drawn from the written application alone, and we hope it is useful well beyond this one process."),
 "s1": paras(
   "The core of the record is solid and measured. Leading end-to-end onboarding for twenty plus SaaS clients at IGate, while holding quarterly business reviews that kept retention and renewals on track, is exactly the kind of work that only shows up well when it is done well. The application also shows a professional who measures the work rather than remembers it: customer health scores, satisfaction metrics and net revenue retention tracked deliberately, risks identified before they became churn. Managing critical escalations and incident resolution to service-level commitments, while keeping twenty client relationships warm enough to renew, is a balancing act the application describes matter-of-factly, which is usually the mark of someone who has actually carried it.",
   "The systems discipline repeats across employers, which tells us it is a habit and not a project. ServiceNow ticketing and workflows implemented at Zones, then configured and optimized again at IGate; service-level compliance managed through escalations rather than around them; and user training delivered so that adoption did not depend on the person who built the workflow staying in the room. The ChurnZero certification and customer success coursework on top show the craft being kept deliberately current, and the repetition across two employers matters: one implementation can be circumstance, two is a method.",
   "And the Air Blue chapter adds a texture the SaaS years cannot: boarding closeouts, seat allocation and passenger issues handled against a departure clock, alongside hands-on network and systems troubleshooting in the same role. A record that holds both quarterly business review decks and TCP/IP diagnostics documents genuine range, and range of that kind tends to compound over a career."),
 "s2": paras(
   "Here is where the decision came from. This seat is an outbound growth-execution role, second chair to our Head of Growth: its daily motion is originating new institutional partnerships inside Pakistan's education ecosystem, with provincial education departments, government institutions and development and donor organizations as counterparties, forty to sixty percent domestic travel, and a pipeline carried personally toward a revenue number. The seat is scoped for someone roughly four to six years into their career, which this record matches in years; the question was never seniority.",
   "The five documented years sit on the other side of the handshake: onboarding, retention and service delivery for clients someone else had already won. What we could not find in the written application was an acquisition record, a new-revenue target originated and closed, or an education-sector or public-sector counterparty anywhere in the file. The role required hunting evidence on Pakistani institutional terrain; the record's proven strength is keeping promises after the sale has been made. Both crafts are necessary to any growth engine. They are not the same craft, and this seat is built entirely around the first one. Nothing in that reading is a deficiency; a growth function without the second craft bleeds every client it wins. It is simply not the seat we are filling right now."),
 "s3": paras(
   "The straightest path is upward through the craft already proven: customer success and service delivery leadership in SaaS, where a ServiceNow-literate operator who genuinely owns net revenue retention is scarce in this market and getting scarcer. If growth-side work is the ambition, the most credible bridge is inside the current role: expansion revenue carried as an owned number, upsells and renewals originated rather than inherited, documented so the next application can show revenue created and not only revenue protected. The Pakistani SaaS and services market is producing more acquisition-heavy companies every year, and nearly all of them under-invest in exactly the retention machinery this file documents; that scarcity is leverage, and it is worth using deliberately.",
   "Our openings live at taleemabad.com, and operations and client-facing roles do appear there as we grow; if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "The same file that runs quarterly business reviews once kept aircraft boarding on schedule. Composure with a clock running is documented across two industries here, and that is not a common line."
},
{
 "app_id": 3881, "first": "Ahmed", "name": "Ahmed Wali", "email": "iwalikhattak@gmail.com",
 "subject": "The specification you authored, and the seat that sells",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Six years that move from writing code to writing specifications deserve a specific reply, so here is an honest account of what we appreciated and exactly where the decision came from.",
   "We write to every applicant this way because a decision should carry its reasoning with it. What follows is grounded entirely in the written application, and much of it, we suspect, will be more useful pointed at your next application than at this one."),
 "s1": paras(
   "The RetroFlow work is the most distinctive thing in the file. A complete PRD, technical specification and rule-engine architecture authored single-handedly for an operations platform in the UK retrofit industry, with a three-layer design spanning rule logic, company configuration and LLM reasoning, plus a dashboard specification covering KPI tracking, a stuck-job queue, SLA monitoring and multi-channel alerting. Producing that entire artifact set from an operational bottleneck identified first-hand, and retaining ownership of the specification and IP, is product work most six-year records do not contain. The featured projects underneath it, a negotiation simulator with live multi-metric scoring, a voice-based training agent, an operations KPI dashboard built on Google Apps Script, repeat the same pattern of picking a real problem and specifying it to the bone.",
   "The Smart Outsource arc is just as coherent. Primary liaison between UK leadership and Pakistan operations; GoHighLevel evaluated, selected and implemented as the company CRM with lead-lifecycle workflows defined through stakeholder interviews; and SOPs documented on ClickUp that supported scaling from roughly fifteen to one hundred and fifty plus employees, with a promotion from compliance executive to eligibility team lead along the way. Building the operational rails a company scales on is verifiable, structural work, and liaison duty between a UK leadership team and a Pakistan operations floor is, quietly, stakeholder management of a demanding kind, done daily across a time zone and a culture gap.",
   "And one sentence in the summary earned particular respect: treating every AI-generated output as a draft, validating it against real requirements, logic and business context before it ships, and staying accountable for the result regardless of how it was produced. With a software engineering degree and a working stack from Python and FastAPI to PostgreSQL underneath it, that is a professional standard written down, not a slogan."),
 "s2": paras(
   "Here is where the decision came from. This seat is a revenue-carrying partnership role, second chair to our Head of Growth: its core motion is originating institutional partnerships with provincial education departments, government institutions and development and donor organizations across Pakistan, with forty to sixty percent domestic travel and a pipeline carried personally toward a number, week after week, in the field. Its CRM is not a system to configure but a queue to empty: names to chase, proposals to send, district offices to sit in until the answer arrives.",
   "The six documented years are analysis, compliance operations, requirements engineering and product specification. What we could not find in the written application was a selling record of any kind: a revenue target carried, a partnership originated and negotiated to closure with an external institution, or a counterparty won rather than served. The CRM chapter is implementation, building the pipeline machinery itself, where this seat spends its days inside the pipeline working deals. The role required a hunter's evidence; this application argues, credibly and in detail, for a builder. To be precise about what that means: nothing here says the selling craft is absent from the person; it says the selling craft is absent from the page, and the page is all a written evaluation can fairly weigh."),
 "s3": paras(
   "The record points somewhere specific, and following it is not a retreat from ambition. Product analyst, business analyst and product operations seats, including in edtech companies whose products serve schools and governments, are exactly where PRD authorship, CRM implementation and scale-up operations experience function as entry evidence rather than adjacent context. The single most valuable next line the file could earn is a shipped RetroFlow: a specification with a build partner, live users and even one paying customer outweighs any specification alone, however complete, because it converts documented thinking into documented outcomes.",
   "Our openings live at taleemabad.com, and product and operations roles do appear there as the organization grows; if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "The line about staying accountable for every AI output regardless of how it was produced is one we read twice. Standards written down before anyone demands them tend to hold; keep that sentence in every version of the document."
},
{
 "app_id": 3882, "first": "Hamza", "name": "Hamza Arshad", "email": "hamza5564@gmail.com",
 "subject": "Two stints at Ropstam, and what the page leaves unsaid",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. We write a full account to every applicant because a decision should arrive with its reasons, and in your case we want to be more direct than usual, in good faith: the main thing standing between this application and serious consideration for roles like this one is the application document itself, and that is fixable.",
   "Everything below comes from the written application alone. Where it is blunt, it is blunt about the page, not about the person behind it, and it is offered because a more guarded letter would be less useful to you."),
 "s1": paras(
   "The most meaningful fact in the file is the shape of the Ropstam chapters: a business development seat held from January 2022 to February 2023, and the same employer opening the door again from October 2024 through April 2026. Organizations rehire people who left work behind worth returning to. That second stint is quiet, verifiable evidence of standards kept, and we weighed it exactly that way. The duties across both stints, proposal writing, project coordination, monthly target completion and client communication for IT services sold into international markets, describe a genuine commercial apprenticeship. Holding monthly targets in international IT services across a combined stretch approaching three years also means rejection absorbed at volume, which is a muscle this profession never stops using.",
   "The range early in the record registered as well: outbound business-to-business outreach to professionals across the Middle East, Africa and Europe at Marcus Evans, with product presentations and LinkedIn lead generation; content strategy, search-optimized writing and e-commerce listings at Vapes Direct; and a public relations year at IEEE UET running sponsorship engagements, campaign planning and training programs, all while completing a computer science degree at UET Lahore. Different rooms, and in each of them, some version of persuading someone to say yes; the computer science foundation underneath gives the technical-services selling a base many business development files in this market cannot show.",
   "Even the activities section, easy to skim past, says something specific: new languages being studied, philosophy read, sessions attended on financial growth. Curiosity maintained off the clock has a way of showing up on it."),
 "s2": paras(
   "Here is the honest center of the decision, in two parts. The first is what the seat needs. This is a hands-on growth-execution role, second chair to our Head of Growth, whose counterparties are provincial education departments, government institutions and development and donor organizations across Pakistan, with forty to sixty percent domestic travel and roughly four to six years of partnership-building depth behind it. The written application does not reach those pillars: the work described is proposal writing and outreach for IT services into international markets, and the education and government arenas do not appear anywhere in the file. That is not a bar this letter invents; it is the published shape of the seat, and every application is weighed against it line by line.",
   "The second is what the page itself withholds. Duties are listed and outcomes are not: monthly targets appear without a single number, proposals without win rates, client relationships without names, sectors or revenue. The salary-expectation field reached us reading simply as unsure, which a closely read form cannot carry. We could only evaluate what was written, and what was written left its own strongest claims unproven. That is the whole distance between this application and a competitive one."),
 "s3": paras(
   "Rebuild the document around results before it goes anywhere else. The Ropstam rehire is the headline, so state what earned it: targets expressed as percentages achieved, proposals converted into projects, accounts held and grown, revenue attached wherever it can honestly be attached. Four years of business development almost certainly contain more evidence than these pages currently show, and every number added moves the file from asserting to proving. Then pick one market and let the next chapter build depth in it, because a record that stacks its wins in one arena reads twice as heavily as the same wins scattered. And decide the salary figure before the form asks; an unsure there hands the reader a doubt for free.",
   "Our openings live at taleemabad.com, across several functions and levels; if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "Two separate stints at the same company is the line we kept returning to. Doors reopen only for people who left them well; make the rest of the page live up to the fact it already proves."
},
{
 "app_id": 3883, "first": "Abdul Waheed", "name": "Abdul Waheed", "email": "waheedbasit@outlook.com",
 "subject": "Six years of lists, sequences, and the missing close",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. The application was read line by line, and because six years of genuine craft sit inside it, we want to give you an honest, specific account of what we appreciated and exactly where the decision came from.",
   "We write to every applicant this way because a decision should carry its reasoning with it. What follows is grounded in the written application alone, and we hope the second half of it is worth keeping."),
 "s1": paras(
   "The prospecting craft is visibly worked, not name-dropped. Verified business-to-business contact lists built with Apollo, LinkedIn Sales Navigator, Crunchbase, Hunter and Skrapp; cold email campaigns managed and optimized through Instantly and Lemlist; qualified leads generated in the thousands across the United States, the United Kingdom and Europe, tracked through HubSpot, Zoho and Salesforce. The modern outbound stack appears here as a set of tools actually used daily, and the thirty four percent plus email open rate is the kind of number that only comes from real iteration. Managing Upwork bidding, client proposals and relationship management at NineSol alongside the outbound machinery shows the craft extends past the first reply and into the winning of actual work.",
   "The Ähdus chapter carries the strongest outcomes: client retention up twenty five percent through consistent follow-ups and personalized communication, partnership opportunities up thirty percent, lead qualification accuracy improved forty percent, and inbound inquiries up twenty eight percent from campaigns built alongside the outreach. A single role that improves the top of the funnel and its hygiene at the same time is doing more than volume work.",
   "And the longer arc has an honest floor under it. Organic traffic up forty five percent and domain authority up twelve points at Pixako, a thirty three percent improvement in lead-to-opportunity conversion in the iCrowdNewswire years, one hundred and twenty percent of monthly sales targets at J Telemarketing, and a start installing broadband and IPTV connections at PTCL with ninety five percent customer satisfaction scores. A record that begins with hardware in hand and ends in Apollo dashboards documents adaptability without needing to claim it."),
 "s2": paras(
   "Here is where the decision came from. This seat's motion is in-person institutional acquisition inside Pakistan: provincial education departments, government institutions and development and donor organizations as counterparties, deals shaped over months of relationship building and formal procurement, forty to sixty percent domestic travel, and a CRM discipline pointed at signatures rather than sequences.",
   "The six documented years are digital, remote and international: lists, campaigns and qualified handoffs for technology services buyers abroad. What we could not find in the written application was a Pakistani institution as a counterparty, a field chapter after the early PTCL years, or a deal carried personally from first contact through negotiation to closure; across employers, the record consistently ends at the qualified lead, where this seat only begins. The availability section also states, in writing, openness to remote roles and evening shifts serving international clients, while this seat spends half of every month on the road between district offices in Pakistan. With one seat to fill, we went with demonstrated evidence on that terrain."),
 "s3": paras(
   "The highest-leverage move this record can make is owning the close. Six years of filling other people's funnels is proven beyond argument; the next chapter should carry one number from first touch to signed agreement, in one chosen vertical, so the file shows revenue closed rather than leads passed. The Ähdus percentages would also land harder with denominators attached, because thirty percent of what is the first question every serious reader asks. One practical note offered in good faith: the expected-salary field in your application form reached us as a figure we could not interpret, so wherever the next application goes, that line deserves a re-check before submitting.",
   "Our openings live at taleemabad.com; if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "From installing broadband connections in 2017 to building verified contact lists across three continents is real distance covered in six years, and the record shows every step of it was worked for, not skipped."
},
{
 "app_id": 3886, "first": "Ahmed", "name": "Ahmed Ur Rehman", "email": "ahmedahmedrehman@gmail.com",
 "subject": "Apna Cheese, ad funnels, and a different arena",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Your application was read closely and in full, and because seven years of hands-on work sit behind it, we want to give you an honest, specific account of what we appreciated and exactly where the decision came from.",
   "We write to every applicant this way for a simple reason: a decision that affects someone's next months should come with its reasoning attached, and the reasoning here is about arenas, not ability, so it is worth spelling out properly."),
 "s1": paras(
   "The current chapter shows genuine end-to-end ownership. Heading digital marketing for the Mian Group of Chakwal means brand strategy and performance marketing across multiple business entities at once: lead generation campaigns run on Meta, Google and TikTok, comprehensive search optimization for local and national traffic, Shopify store operations with listing optimization and conversion funnels, AI tools integrated for content generation and workflow automation, and creative teams coordinated against return-on-ad-spend targets. That is a full growth stack carried by one head.",
   "The Millennium Builders chapter adds depth in a hard vertical. Real estate campaigns that generated high-volume qualified buyer leads, key commercial search queries ranked organically, and a company YouTube channel run genuinely end to end, from content strategy through production and tagging to audience growth, with scripts and funnels built to accelerate property sales. Few marketers hold both the paid and the organic side of one market at that level of detail.",
   "And then there is Apna Cheese: a self-owned e-commerce brand at apnacheese.com with Shopify operations, WhatsApp ordering and nationwide logistics, run alongside a full-time head-of-marketing seat. Ownership demonstrated with inventory, orders and delivery riders is a different credential from ownership claimed in a summary paragraph, and we read it exactly that way."),
 "s2": paras(
   "Here is where the decision came from. This seat is a hands-on growth-execution role inside Pakistan's education ecosystem, second chair to our Head of Growth. Its counterparties are provincial education departments, government institutions and development and donor organizations; its deals are shaped by relationships, proposals and formal procurement over months; its rhythm is forty to sixty percent domestic travel and a personally carried CRM pipeline of institutional opportunities.",
   "The seven documented years acquire customers one funnel at a time: ad platforms, search rankings, landing pages and conversion rates, mostly for consumer, retail and property buyers. What we could not find in the written application was an institutional counterparty of any kind, education-sector or public-sector work, or a deal won through relationship building and procurement rather than through an auction dashboard. The craft in the file is real and current; the arena is simply different, and this seat lives entirely in the other one. With a single seat to fill, we went with records proven on institutional terrain."),
 "s3": paras(
   "Keep compounding where the record is strongest. Performance and growth marketing seats at consumer edtech products, e-commerce companies and property platforms are the natural next rooms for this file, and in every one of them the Apna Cheese chapter deserves the top of the page, with its numbers made explicit: monthly orders, repeat purchase rates, cities served, ad spend against revenue. The file names return-on-ad-spend and conversion tracking as daily practice; publishing three of those actual figures would convert a confident document into an undeniable one.",
   "Our openings live at taleemabad.com, and consumer-facing growth roles do appear there as our products expand; if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "A cheese brand with nationwide delivery, built and run while holding down a head-of-marketing job, is the detail we kept returning to. People who ship their own ideas are rarer than the word entrepreneur suggests."
},
{
 "app_id": 3887, "first": "Usama", "name": "Usama Hashmi", "email": "usama1311@gmail.com",
 "subject": "Fifteen years, seven markets, and two structural facts",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. A fifteen-year record spanning Pakistan, Australia and the United States deserves a precise reply rather than a template, so here is exactly what we appreciated and exactly where the decision came from.",
   "In your case the decision rests on two structural facts about the seat rather than on the quality of the record, and you deserve to hear both stated plainly, because a vaguer letter would leave you guessing at things we can simply tell you."),
 "s1": paras(
   "The OrbisPay chapter is the record's center of gravity. Reporting directly to the chief executive of a Boston fintech, building the sales organization from hiring through coaching, owning the tool stack from HubSpot and Salesforce to Outreach and ZoomInfo, and generating a pipeline of three hundred qualified opportunities across accounts employing more than three hundred and five thousand people, with potential annual revenue of 17.5 million dollars. Building the machine and filling it at the same time is the hard version of the job.",
   "The foodpanda chapter shows what the record does under pressure: four hundred percent order growth within roughly ten days during the COVID lockdown, two hundred and fifty home chefs signed onto the platform, delivery times cut by eight minutes and cancellation rates held under two percent, with a new channel development segment launched alongside. Crisis weeks are when operating instinct becomes a matter of record, and that week is documented.",
   "The UNAIDS engagement matters to us specifically: an HIV financing assessment run on the globally standardized NASA methodology at national and provincial levels, covering public and development-partner resources, producing an expenditure report built to feed revisions of national and provincial AIDS strategy. And the Australian years underneath it all, a sales team grown from three to fourteen at Paloma and three hundred and eighty new products introduced to market, show the standard held across borders and industries."),
 "s2": paras(
   "Here are the two structural facts. First, compensation: the expectation you shared sits well above what this role carries. That is not a gap a process narrows; it is how the seat is graded, and we would rather state it now than spend weeks of your time arriving at the same arithmetic.",
   "Second, altitude. This is a second-chair, hands-on execution seat reporting to our Head of Growth, scoped for someone roughly four to six years into their career, whose weekly reality is personally carried CRM discipline, drafting the follow-ups and sitting in district waiting rooms across forty to sixty percent domestic travel. The record in the application is director-level and chief-executive-adjacent, fifteen years deep. The seat would use a fraction of the leadership scope documented here, and that arithmetic serves neither side. We would add one texture note: the development-sector chapter was research consulting, and the acquisition chapters ran through American and Australian commercial markets, so Pakistani institutional partnership acquisition as a sustained core motion is also not in the file. But the two structural facts alone decided it."),
 "s3": paras(
   "Aim where the record already points: commercial leadership and business development director seats at fintechs, marketplaces and development-sector-adjacent organizations, where a chief-executive-reporting build like OrbisPay is the entry credential rather than an overshoot, and where the UNAIDS chapter reads as a bridge instead of an outlier. One document note offered in good faith: several recent chapters run short, and the file currently leaves the reader to supply the context on their own; a single factual line stating the circumstance of each transition would keep that narrative in your hands, where it belongs.",
   "Our openings live at taleemabad.com, and the organization is growing; if a larger-scope role opens, we would welcome a fresh application from you."),
 "ps": "Four hundred percent growth in ten days, in the middle of a lockdown, is the detail we kept returning to. Numbers like that cannot be polished into a CV afterwards; they can only be earned at the time."
},
]

built = []
for e in EMAILS:
    html = TEMPLATE
    html = html.split("<!DOCTYPE")[1]
    html = "<!DOCTYPE" + html  # drop the top comment block
    html = html.split("<!--\nCV REJECTION RULES")[0]  # drop trailing rules comment
    html = html.replace("[SUBJECT_LINE]", e["subject"])
    html = html.replace("[ROLE]", e["role"])
    html = html.replace("[CANDIDATE_FIRST_NAME]", e["first"])
    html = re.sub(r'<p style="margin:0 0 18px 0;[^"]*">\[OPENING_PARAGRAPH:[^\]]*\]</p>', e["opening"], html)
    html = re.sub(r'<p style="margin:0 0 18px 0;[^"]*">\[SECTION_1_CONTENT:[^\]]*\]</p>', e["s1"], html)
    html = re.sub(r'<p style="margin:0 0 18px 0;[^"]*">\[SECTION_2_CONTENT:[^\]]*\]</p>', e["s2"], html)
    html = re.sub(r'<p style="margin:0 0 18px 0;[^"]*">\[SECTION_3_CONTENT:[^\]]*\]</p>', e["s3"], html)
    html = html.replace("[PS_CONTENT: one memorable, character-affirming line tied to a specific moment.]", e["ps"])
    html = re.sub(r'<!-- \[FEEDBACK_WIDGET\][^>]*-->', '<!-- FEEDBACK_WIDGET_HERE -->', html)
    assert "[" not in re.sub(r'<!--.*?-->', '', html, flags=re.S), f"unfilled placeholder in {e['name']}"
    path = os.path.join(OUT, f"{e['app_id']}_{re.sub(r'[^a-zA-Z0-9]', '_', e['name'])}.html")
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    words = len(re.sub(r'<[^>]+>', ' ', html).split())
    built.append((e["app_id"], e["name"], path, words))
    print(f"built {e['app_id']} {e['name']}: ~{words} words -> {path}")
