# -*- coding: utf-8 -*-
"""Job 42 CV-rejection feedback emails, BATCH 03 (10 candidates from wave_batches/batch_03.json).
Layout: templates/cv_rejection_template_locked.html (v8, LOCKED, placeholders only).
Rules: 800+ words, CV-only evidence (no fabricated interaction), no em dashes, we-voice,
role-fit framing, no intent inference, candidate-initiated reapplication, no abstractions.
Outputs: output/job42/rejection_emails/<app_id>_<name>.html
DRAFTS ONLY. Nothing in this script sends email.
"""
import os, re

TEMPLATE = open(r"c:\Agent Coco\templates\cv_rejection_template_locked.html", encoding="utf-8").read()
OUT = r"c:\Agent Coco\output\job42\rejection_emails"
os.makedirs(OUT, exist_ok=True)

P = ('<p style="margin:0 0 18px 0;text-align:justify;font-family:Georgia,serif;'
     'font-size:15px;line-height:1.8;">{}</p>')

def paras(*texts):
    return "".join(P.format(t) for t in texts)

ROLE = "Senior Manager Growth · Taleemabad"

EMAILS = [
{
 "app_id": 3903, "first": "Ansar", "name": "Ansar Nadeem", "email": "ansar2716362@gmail.com",
 "subject": "Thirty-five thousand women onboarded, and the partnership question",
 "role": ROLE,
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Your application was read in full, and a record built across seven plus years of field programs in Punjab deserves an honest, specific account of what we appreciated and where the decision came from, so that is what follows.",
   "We write to every applicant this way for a simple reason: a decision that affects someone's next months should carry its reasoning with it. Everything below is grounded in the written application you submitted and nothing else, and we hope it is useful well beyond this one process."),
 "s1": paras(
   "The scale of your field delivery is real and documented. Onboarding 35,000 plus women onto CIRCLE's Circle Baji digital platform across an assigned region, while delivering advanced business development training to 5,500 plus women entrepreneurs in business management, marketing, financial planning and growth strategy, is program execution at a volume most coordinators never reach. Numbers like these are earned district by district, and the application shows the machinery behind them: enrollment, scheduling and training delivery run since the Digital Literacy Program's January 2025 launch across Central Punjab.",
   "Second, the institutional web you built to make that delivery possible. Partnerships with twenty plus institutions, including TEVTA, PVTC, University of Lahore, UMT, COMSATS and twenty three Government Women Colleges across Gujranwala Division, show someone who can walk into a public institution and leave with a working agreement that holds. That is a genuinely scarce craft, and it is the part of your record closest to our own work.",
   "Third, the outcomes layer. Facilitating market access for 2,650 plus women entrepreneurs through exhibitions, trade fairs and business expos, with an estimated thirty percent income increase among participants, connects activity to livelihoods rather than stopping at attendance counts. And the reporting discipline named in the application, weekly, monthly and quarterly reports with budget forecasts built in Google Sheets, alongside regular field visits to monitor execution quality and mentor field teams, tells us the delivery was managed, not just done.",
   "The earlier chapters carry the same signature: CNIC registration drives, needs assessments and literacy centers at FACES Pakistan, then non-formal schools, subject-based teacher training and parent-teacher associations at GODH. Seven plus years of this work, built on an MPhil in Sociology, reads as a career grown deliberately inside communities rather than around them."),
 "s2": paras(
   "Here is where the decision came from. This seat is the hands-on execution engine of our growth function, working as second to our Head of Growth. Its job is to win new partnerships: commercial and funded agreements with provincial education departments, government bodies and development and donor organizations, carried personally through a CRM with pipeline targets, proposal cycles and forty to sixty percent domestic travel to close institutional relationships in the field. The seat is also based in Islamabad, and its calendar is owned by deal cycles rather than by program cycles.",
   "The partnership record in your application, and we want to be precise here, sits on the delivery side of that world. The institutions you engaged were counterparties for running funded programs: venues, enrollment channels and training platforms. What we could not find in the written application was a chapter in which winning the agreement itself was the job, where revenue or a signed partnership was the target the work was measured against, or where a commercial pipeline was built and carried end to end. The role required that acquisition motion as its daily core, and with one seat to fill we went with evidence we could read directly on that terrain."),
 "s3": paras(
   "Our suggestion is practical. The distance between program partnerships and commercial partnerships is shorter than it looks, and your record already contains the raw material: public institutions engaged, agreements landed, delivery honored. If growth work attracts you, restate those wins in acquisition terms on the CV: how many of the twenty plus institutional partnerships you initiated rather than inherited, what each one took to open, and what measurable value flowed through them. A development-sector employer hiring for partnerships will read that version of the same record very differently.",
   "Alternatively, the record as it stands is a legible credential for senior program delivery and coordination roles in livelihoods, digital inclusion and education programs, where 35,000 onboarded users is the headline rather than the context, and where the coordination habits you describe with M&amp;E, Outreach and Communications units are exactly what delivery leadership requires. Our openings live at taleemabad.com; if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "The detail we kept returning to: an estimated thirty percent income increase for 2,650 women who reached markets through fairs and expos you organized. Most program metrics count attendance. Yours counted livelihoods."
},
{
 "app_id": 3904, "first": "Mehwish", "name": "Mehwish", "email": "mehwisharjeel@gmail.com",
 "subject": "Fifty percent higher test scores, and the shape of this seat",
 "role": ROLE,
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. A record of fifteen plus years in Pakistani education deserves better than a form letter, so what follows is an honest, specific account of what we appreciated in your application and exactly where the decision came from.",
   "We write this way to every applicant because a decision should carry its reasoning with it. Nothing below is a verdict on the career described; it is an account of the fit between one specific seat and one specific written record, and we have tried to keep that distinction visible throughout."),
 "s1": paras(
   "The Mazen Schools chapter documents leadership with outcomes attached. A ten percent increase in student enrollment over four years, a fifty percent improvement in student test scores driven through curriculum implementation and assessment reforms, and recruitment, professional development and performance reviews carried for one hundred plus staff: that is a principalship measured in results rather than tenure, and the Best Leadership Award in 2019 sits on top of it as external confirmation.",
   "The Roots International years extend the same pattern to network scale. Directing large-scale teacher training across multiple campuses, reaching ninety five percent audit compliance by streamlining quality assurance processes, and building monitoring frameworks and KPIs to track adoption of digital learning tools: this is the unglamorous system-building that actually moves teaching quality, and Best Employee of the Year 2024 tells us the organization saw it that way too.",
   "We also noted the range and the appetite. From classroom teaching at The City School, through two principalships, to a head-office quality and training role, and now a PhD in Social Sciences in progress alongside an MS in Development Studies from SZABIST: the arc shows someone who kept widening the lens on education rather than settling into one comfortable altitude. The stated commitment in your summary to equitable, technology-enabled learning across Pakistan is one we share as an organization, word for word.",
   "Even the less obvious chapters hold up under a close reading. At The Smart School you paired instructor training on methodology and digital adoption with budgeting, compliance and outreach responsibilities, which is operational range beyond the usual principalship. And the current chapter at Goldbox, delivering performance and goal-setting sessions for e-commerce and sales teams, shows a training craft being carried into an entirely new commercial arena rather than resting where the credentials are already recognized."),
 "s2": paras(
   "Here is the honest center of the decision. This seat is not an education-leadership role; it is a commercial one. It works as a hands-on second to our Head of Growth, personally winning new partnerships with provincial education departments, government bodies and development and donor organizations, carrying a pipeline through a CRM, and spending forty to sixty percent of its weeks traveling to districts and partner sites. The daily texture is follow-ups written personally, district office visits, and records kept current by the person who owns them. It is also deliberately scoped for someone roughly four to six years into their career.",
   "Your written application documents fifteen plus years of academic leadership: training, quality assurance, curriculum and school operations. What we could not find in it was the specific motion this seat lives in, institutional agreements pursued, negotiated and closed as the primary job, with revenue or signed partnerships as the measure. And the seniority runs the other way: the role sits at an altitude your career passed a decade ago. Placing a fifteen-year education leader into an early-career execution seat would serve neither you nor the seat, and that judgment, not the quality of your record, is what decided this."),
 "s3": paras(
   "Our suggestion is to aim at the altitude and the craft you have actually built. Edtech organizations and school networks in Pakistan hire for academic quality, teacher development and implementation leadership, seats where a fifty percent test-score improvement and network-level audit compliance are the entry credentials rather than the context. An application aimed there argues for itself, and the PhD in progress is an asset on that path too, because implementation leadership in edtech increasingly asks for research fluency alongside operational depth. It would also be worth putting the Roots training numbers on the page: campuses covered, teachers trained, adoption rates tracked. The record clearly earned those figures, and the document currently states them in general terms.",
   "Our openings live at taleemabad.com, and as we grow, roles in academics, teacher development and implementation leadership do open alongside commercial ones; if a matched role opens, we would welcome a fresh application from you."),
 "ps": "Two awards, five years apart, at two different institutions: Best Leadership Award 2019 and Best Employee of the Year 2024. Excellence that travels between employers belongs to the person, not the position."
},
{
 "app_id": 3905, "first": "Abdullah", "name": "Abdullah Mirza", "email": "abdullah_mirza1@outlook.com",
 "subject": "Two hundred million rupees delivered, read closely",
 "role": ROLE,
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Your application was read in full, and because it documents real delivery in one of the most demanding procurement environments in the country, we want to give you a specific, honest account of what we appreciated and where the decision came from.",
   "We write to every applicant this way because a decision should carry its reasoning with it. Everything below comes from the written application alone, and we hope the reasoning is useful wherever you take the record next."),
 "s1": paras(
   "Five plus years at AMCO Engineering, securing and delivering PKR 200 million plus of defense-sector projects for the Pakistan Army, Navy and Air Force, is the headline, and it is a serious one. Trailers, bowsers and mobile communication vehicles are not products that forgive sloppiness. Contracts of that kind are won on technical and financial bids that survive scrutiny, and the application describes exactly that: competitive bids built on market analysis and cost modeling, with compliance and on-time delivery held through the full project lifecycle.",
   "The breadth around the bidding is what makes the record more than a sales story. End-to-end project lifecycle management, procurement and vendor negotiations, inventory control and supply chain optimization: you did not just win the contracts, you carried them to delivery. And the partnership list, CARE Pvt Ltd, Pak Datacom, Frontier Works Organisation and NRTC, shows relationships built with exactly the kind of institutional counterparties most early business development careers never touch.",
   "The skills section reads like the job was lived rather than listed: contract bidding and negotiation, financial and technical bid development, risk assessment and mitigation, logistics and inventory control. Each of those has a matching bullet in the AMCO chapter, which is the internal consistency we look for when a written application is all we have to go on.",
   "We also noted the earlier and parallel signals: Secretary General and then Director General of the Youth IVY Leadership Olympiad across two consecutive years, a German language summer school and a Chinese language program at Beijing Language and Culture University, and a Business Administration degree from the University of Hertfordshire completed in 2025 while the delivery record above was already being built. Holding a demanding commercial seat while finishing a degree is its own evidence of capacity, and the self-driven coursework in web development and e-commerce points the same direction."),
 "s2": paras(
   "Here is where the decision came from. This seat is the hands-on execution second to our Head of Growth, in education rather than defense. Its counterparties are provincial education departments, government bodies and development and donor organizations; its motion is relationship-led field acquisition, forty to sixty percent domestic travel, long cycles of visits and proposals managed through disciplined CRM and pipeline routines; and it is based in Islamabad with school systems, not workshops, at the end of the road. Those are different waiting rooms from the ones tender work runs through, and the distance between them is the substance of this decision.",
   "Your government-facing experience is real, but the written application documents a different motion: tender-driven bids into procurement offices for engineered hardware, all of it within a single employer and a single sector since 2020. What we could not find in the application was work inside education or the development sector, an acquisition rhythm built on field relationships and pipeline management rather than bid submissions, or exposure to the donor and public-education counterparties this seat faces daily. The role required proven craft on that specific terrain, and with one seat to fill we went with records we could verify there."),
 "s3": paras(
   "Two practical suggestions. First, make the record legible in growth terms: state how many bids you submitted and won, the hit rate, the average contract size and the repeat business earned, because those numbers turn a business development title into a measurable acquisition record any employer can price. If the ratio is as good as the delivery record implies, it belongs at the very top of the CV. Second, if the impact sector genuinely interests you, your fluency in government procurement transfers directly to organizations that win public contracts in health, connectivity and education infrastructure; one deliberate chapter there would connect your bidding craft to the terrain sector employers need it proven on.",
   "A record like yours does not need reinventing, only translating for each new arena. We post openings at taleemabad.com as they go live, across commercial and operational roles; if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "Most people finish a degree and then go looking for their first serious project. You finished yours in 2025 with two hundred million rupees of delivered projects already behind you."
},
{
 "app_id": 3906, "first": "Zainab", "name": "Zainab Sultan", "email": "zainabsultan837@gmail.com",
 "subject": "A Dean's Honour Roll start, and a question of timing",
 "role": ROLE,
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Your application was read in full, and because it belongs to a career at its very start, we want the reasoning to be specific enough to be useful for the decisions ahead of you. Here is an honest account of what we appreciated and where the decision came from.",
   "We write this way to every applicant because a decision should carry its reasoning with it. What follows is grounded entirely in the written application you submitted, and in nothing else."),
 "s1": paras(
   "The academic record is genuinely distinguished. A Master's in Education Leadership and Management from LUMS at a 3.86 CGPA, a place on the Dean's Honour Roll, three merit scholarships, and graduate teaching roles across two courses, built on a BS in English Literature from Air University, is not an ordinary start; it is the profile of someone one of the country's most selective universities repeatedly chose to keep close.",
   "The research chapter matters even more to us. As Research Associate on the DARE-RC project with the Punjab Education Foundation, you coordinated qualitative and quantitative research across multiple schools in Punjab, managed focus groups, classroom observations and institutional data, collaborated with school leaders, teachers, researchers and policymakers, and produced analytical reports under quality assurance procedures. That is real fieldwork inside the exact ecosystem we serve, and the research topics you chose, from teachers' readiness for AI to attendance disparities in Balochistan and the classroom experiences of minority students, show an instinct for questions that matter.",
   "The teaching record reinforces it. Serving as graduate teaching assistant for School Effectiveness and Development and, before that, for Trauma-Informed Education Systems means two different faculty teams trusted you with curriculum implementation, assessments and student support on courses that sit close to the practical heart of school improvement. Course titles like those are not decoration on a transcript; they are the vocabulary this sector actually works in.",
   "The breadth is also visible: brand strategy, partnership development and employer branding at ImagineArt, a finance and legal internship at the Ministry of Foreign Affairs, and a long run of AIESEC directorships spanning international relations, business development and social development projects. For someone this early, the surface area is unusually wide, and the event leadership at the Pehla Sabaq Literary Festival and the graduate seminar series shows the same follow-through in operations as in coursework."),
 "s2": paras(
   "Here is where the decision came from, and it is structural rather than qualitative. This seat is scoped for someone roughly four to six years into a career of commercial growth execution: personally winning partnerships with provincial education departments, government bodies and donor organizations, carrying a pipeline through a CRM, and traveling forty to sixty percent of the time to close institutional relationships in the field. The written application documents a career of roughly one to two years, built in research, teaching support and early brand work, without yet a chapter in which acquiring partnerships or carrying revenue was the job.",
   "There is also a second structural fact we want to name plainly: the compensation expectation you shared sits well above what this role carries, by a wide margin. Either fact alone would have led to the same decision; together they make it clear that this is about the distance between one seat and one moment in a career, not about the caliber of the record."),
 "s3": paras(
   "Our honest suggestion is to spend the next two to three years building an execution record inside the education sector you have already studied from the inside. Roles in education programs, partnerships support or research-to-policy work around the Punjab Education Foundation ecosystem would let the DARE-RC fieldwork compound into delivery experience, and the LUMS network is unusually well placed to open those doors. When the record shows partnerships or programs you carried yourself, applications for growth seats will argue from evidence rather than promise, and two or three years from now the same application with an execution chapter added would be a different document entirely. It would also help to align the stated compensation expectation with the market for early-career roles, because a figure far outside that band can end an otherwise serious application before it is fully read.",
   "Our openings live at taleemabad.com, across research, program and commercial roles as we grow; if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "The research topics stayed with us: attendance disparities in Balochistan, the classroom experiences of minority students. Choosing hard, unfashionable questions at the start of a career says something a CGPA cannot."
},
{
 "app_id": 3907, "first": "Aliha", "name": "Aliha Zainab", "email": "alihazainabbukhari@gmail.com",
 "subject": "Seven hundred careers coached, and a question of arena",
 "role": ROLE,
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Your application documents nearly a decade of people work at real scale, and it deserves an equally real explanation, so here is an honest, specific account of what we appreciated and where the decision came from.",
   "We write to every applicant this way because a decision should carry its reasoning with it. Everything below is grounded in the written application alone, and we hope it is useful well beyond this one process."),
 "s1": paras(
   "The volume and verifiability of the record stood out first. Recruiting and managing the hiring lifecycle for two hundred plus technical and non-technical roles, drives of eighty seven plus hires run simultaneously, five hundred fellows selected from a pool of 1,200 plus applicants for the PepsiCo Roshan Kal internship at Amal Academy, and forty plus hires closed within four months for a Canadian startup: these are delivery numbers, not adjectives, and the application states them with dates and employers attached.",
   "Second, the training and coaching arc. Seven hundred plus individuals trained and mentored across career development, communication and leadership, two hundred plus one-on-one counseling engagements, an eighty percent post-career-lab placement rate at Grey Matter Global, and Amal Academy cohorts graduating one hundred forty plus fellows with eighty seven percent launching professional careers by post-program survey data. Structured, measured capability building runs through every chapter of the record.",
   "Third, the systems instinct underneath. KPI-driven promotion frameworks at P3A, fifty plus process audits across engineering operations at Devsinc, compensation benchmarking, handbook builds and policy frameworks at Aterna Advisors, and workforce data maintained for 1,500 plus records. Add a NUST master's in Human Resource Management, a published case in the Asian Journal of Management Cases, and a final-year project funded by the United States Institute of Peace, and the record reads as a people-operations professional who documents what she builds.",
   "The P-TEVTA chapter compressed the whole toolkit into one summer: 1,000 CVs reviewed, 850 candidates advanced to the employment test, 89 interns onboarded, and 23 teams monitored and evaluated across the internship, alongside an organizational audit and a talent strategy. A ten-week engagement that produces numbers like those explains why the later chapters kept handing you bigger mandates."),
 "s2": paras(
   "Here is where the decision came from. This seat is a commercial one: the hands-on execution second to our Head of Growth, personally winning partnerships with provincial education departments, government bodies and development and donor organizations, carrying pipeline targets through a CRM, and traveling forty to sixty percent of the time to build institutional relationships in the field, with the follow-ups, the district visits and the record-keeping done personally rather than delegated.",
   "Your record is deep, but its counterparties are overwhelmingly internal: employees, candidates, fellows and leadership teams. The closest the application comes to commercial ground is the Devsinc chapter, where tailored proposals and candidate profiles supported B2B engagements with clients in MENA and beyond, and that work sat inside a staffing motion rather than a partnerships one. What we could not find in the written application was a chapter in which external institutions were won as partners, where revenue or signed agreements were the measure, or where a commercial pipeline was carried end to end. Talent work and growth work share vocabulary, but they are different crafts practiced on different terrain, and the role required the second one already proven. With one seat to fill, we went with evidence we could read directly on that terrain."),
 "s3": paras(
   "Our suggestion is to aim where the record is already senior. Education and development-sector organizations in Pakistan hire hard for exactly what you document: capability building at scale, HR systems that survive audits, and cohort programs delivered with measured outcomes. Seats in people and culture leadership, capacity building or program delivery would treat your seven hundred plus trained and your placement rates as the headline credential rather than background. If commercial work genuinely attracts you, the honest bridge is a role with an explicit external target, partnerships or institutional sales, held deliberately for two to three years so the record can show that motion in closed agreements. The Salamti peace-building fellowship and the interfaith storytelling workshop you organized for 190 plus students belong in that story too, because development-sector employers read them as sector fluency, not extracurriculars.",
   "Our openings live at taleemabad.com, and people and culture roles do open as we grow; if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "Gold Medalist across a Stanford-affiliated fellowship, then years spent putting seven hundred other people through the same kind of growth. Careers that pay forward what they win are rarer than the CV format lets on."
},
{
 "app_id": 3908, "first": "Khayam", "name": "khayyam khawar", "email": "khayyamkhawar@outlook.com",
 "subject": "Twenty playbooks, a number two ranking, and the front of the funnel",
 "role": ROLE,
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Your application was read in full, and because it makes a deliberate, well-argued case in writing for moving from the execution side of growth to the front of the funnel, it deserves a precise answer rather than a template. Here is an honest account of what we appreciated and where the decision came from.",
   "We write this way to every applicant because a decision should carry its reasoning with it. Everything below is grounded in the written application alone."),
 "s1": paras(
   "The retention-side record is documented with unusual discipline. Ranked second across the entire SurePoint Technologies organization for peer and leadership recognition, a twenty seven percent reduction in escalations achieved through CRM hygiene and early blocker identification, and satisfaction scores held above ninety percent across every role at daily volumes of two hundred plus combined interactions. These are numbers a hiring team can verify, and they describe someone clients and colleagues repeatedly chose to trust.",
   "Second, the playbook instinct. Twenty plus SOPs and knowledge-base playbooks authored at SurePoint that cut onboarding time by twenty percent, internal SOPs at RDX Sports that became the execution backbone for new team members, Google Sheets dashboards that cut resolution time by eighteen percent through earlier intervention. Turning personal competence into repeatable frameworks other people can run is among the most transferable skills in operations, and it appears in every chapter of the application.",
   "Third, the current arc. Owning client onboarding and adoption end to end at Pam.ai on US hours, serving as the primary point of contact for escalations with full ownership until closure, and deploying generative AI tools to cut documentation time by more than sixty percent while improving outreach consistency. The record shows a professional who keeps modernizing the toolkit rather than defending the old one.",
   "Even the earliest chapters carry the pattern: satisfaction held above ninety percent at Motive while handling well over a hundred combined contacts a day and mentoring new team members into independent execution, and onboarding materials built at PKTeam that standardized the client experience for the whole team. Consistency across five employers is its own form of evidence."),
 "s2": paras(
   "Here is where the decision came from, stated plainly. This seat is the front of the funnel itself: the hands-on execution second to our Head of Growth, personally winning new partnerships with provincial education departments, government bodies and development and donor organizations in Pakistan, with forty to sixty percent domestic travel and field acquisition as the weekly rhythm. The written record sits on the post-deal side of that world: onboarding, adoption, retention and support, delivered remotely for North American SaaS, legal and accounting clients. What we could not find in the application was a chapter in which new institutional partnerships were won as the primary job, or in which government or education institutions in Pakistan were the counterparties.",
   "We also want to be plain about the overlap, because it is real: the CRM discipline the application documents, Salesforce, HubSpot, Zendesk and Zoho kept clean at volume, is genuinely how this seat runs its week. It was the counterparty and the deal-side evidence that were not there, not the operating hygiene. And there is a structural fact to name: the compensation expectation you shared sits well above what this role carries. Either gap alone would have shaped the decision; together they settled it. None of this reads against the record itself, which is consistent and verified; it is about which terrain that record has been proven on so far."),
 "s3": paras(
   "The bridge your summary describes is real, and there is a practical way to cross it: a seat where an explicit acquisition number is yours, new accounts, new partners or new institutions, so that the next application can show the front-of-funnel motion in closed agreements rather than in positioning. Given the CRM discipline and the SOP authorship already on the record, account management with a growth quota, or partnerships execution at a SaaS or services firm, would let the existing evidence carry over directly while the new evidence accumulates. Two years of that produces an application no growth team can set aside easily.",
   "The direction you have chosen is legible in the record; what it needs next is one chapter of proof. We post openings at taleemabad.com as they go live; if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "A number two ranking across an entire company, voted by peers and leadership, cannot be self-authored. Whatever funnel you end up in, that kind of standing follows the person who earned it."
},
{
 "app_id": 3912, "first": "Zain", "name": "zain ul abdin", "email": "zainulabideen0094@gmail.com",
 "subject": "The best ROAS in the account's history, and a different motion",
 "role": ROLE,
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Your application shows four years of performance marketing with results worth naming precisely, so rather than a form letter, here is an honest account of what we appreciated and exactly where the decision came from.",
   "We write to every applicant this way because a decision should carry its reasoning with it. Everything below is grounded in the written application you submitted, and we hope it is useful wherever you apply next."),
 "s1": paras(
   "The ShaPosh chapter is the standout. Rebuilding an ad account's structure and then launching a catalog campaign that delivered the highest ROAS and the lowest CPA in the account's recorded history is a before-and-after any growth practitioner understands instantly. Alongside it, standing up an email channel through Mailchimp and scaling it past five thousand dollars a month in revenue shows channel-building from zero, not just optimization of what already worked.",
   "The range across the four years also registers. Full-funnel Facebook strategy with creative testing, budget optimization and audience refinement, Google Ads campaigns run to complement paid social, TikTok initiated as part of an omni-channel push, and conversion-rate research carried through to landing page changes. At Khushi Media you ran lead campaigns for Khushi Motors, one of the largest car dealership groups in Africa, and the application notes something we value: conversion rates improved by working directly with the sales team to fold on-ground customer insight back into the marketing.",
   "And the earliest chapter shows the same commercial instinct in a harder setting. At Rise Plastic, targeted lead campaigns and close customer relationships expanded a manufacturer's reach into multiple new cities while keeping inventory aligned with demand. Growing an unglamorous product with paid media is often better evidence than growing a glamorous one, and a commerce degree with a marketing specialization plus a debating club presidency round out a record built step by step.",
   "The record also shows a practitioner who keeps sharpening the toolkit: certifications in Google Ads PPC, Performance Max campaigns through Adventure Media in New York, and structured marketing coursework, with the degree itself finished while the Rise Plastic campaigns were already running. Learning bought with your own evenings tends to stick."),
 "s2": paras(
   "Here is where the decision came from. This seat acquires growth in a different way than your record documents. It is the hands-on execution second to our Head of Growth, and its motion is institutional: winning partnerships with provincial education departments, government bodies and development and donor organizations, through proposals, field visits and long relationship cycles, carried in a CRM with pipeline discipline and forty to sixty percent domestic travel out of an Islamabad base. Its weeks are spent in district education offices and partner meetings rather than in an ads manager, and its wins are signed agreements that take months, not campaigns that read out overnight.",
   "Your acquisition craft is digital: audiences found and converted through paid channels, measured in ROAS and CPA. It is real craft, and nothing here argues otherwise. But what we could not find in the written application was work with institutional counterparties, in-person deal cycles that run across months, or the education and development sector at all. The role required that specific motion already proven, and with one seat to fill we went with records we could verify on that terrain."),
 "s3": paras(
   "Our suggestion is to double down rather than pivot. Performance marketing is bought as its own seat by every serious consumer and edtech growth team in the country, and your ShaPosh numbers are the exact shape of evidence those teams hire on. Package the turnaround as a one-page account: the starting ROAS and CPA, what you rebuilt, the ending ROAS and CPA, and the revenue now flowing through the email channel, and let that page lead every application. Keep the Khushi Motors chapter on it too, because an international client, monthly targets exceeded and marketing tied directly to a sales floor is a story institutional employers also understand. If institutional growth work attracts you later, the practical path is a hybrid seat in an organization that runs both motions, where paid acquisition is your entry credential and field partnerships are learned alongside it.",
   "Our openings live at taleemabad.com, including digital and marketing roles as we grow; if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "Beating an account's entire recorded history for both ROAS and CPA in the same campaign is the kind of line most marketers wait a career to write. You wrote it four years in."
},
{
 "app_id": 3913, "first": "Tooba", "name": "Tooba Saleem", "email": "toobasaleeem@gmail.com",
 "subject": "Forty-eight million views for education reform, and the shape of this seat",
 "role": ROLE,
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Your application sits closer to our world than the decision below might imply, which is exactly why it deserves a precise explanation. Here is an honest account of what we appreciated and where the decision came from.",
   "We write this way to every applicant because a decision should carry its reasoning with it. Nothing that follows is a verdict on the record; it is an account of fit between one seat and one written application."),
 "s1": paras(
   "The reach numbers are extraordinary and, unusually, fully documented: 48.2 million Facebook views and 12.6 million Instagram views over seventeen months, a 4,800 percent year-on-year jump in Instagram reach, 832 thousand followers added, and more than 1,561 days of total watch time. Most applications claim growth in adjectives; yours publishes the platform analytics with the organic and paid split included, and that transparency is itself a credential.",
   "More important to us than the volume is what the volume was built on. Positioning Zindagi Trust as a leading voice in systemic education reform, translating teacher education and policy into content mass audiences actually consume at Durbeen, with 474.8 percent organic reach growth and a 215 percent following increase, and running diaspora campaigns across the US, UK, Canada and UAE tied to advocacy and fundraising. This is education-sector storytelling with donor engagement systems behind it, alongside campaign work with DW Akademie, UNDP and iVerify Pakistan through the IBA Centre for Excellence in Journalism chapter.",
   "And the record shows a builder as well as a broadcaster: structured donor communication systems that improved response time and retention, content planning and design systems introduced at Alpha Education Network that lifted enrollment inquiries, and corporate, media and CSR partnerships managed for national visibility. Seven plus years, nearly all of it in or around education and development, is a rare through-line in this market.",
   "The freelance decade underneath adds still more range: campaigns on misinformation, civic engagement and mental health awareness delivered with DW Akademie, UNDP, German Cooperation and the US Consulate, visual identity systems and event branding held to international standards, and high-visibility drives like the Ramadan and back-to-school campaigns at Zindagi Trust. An MBA in Marketing from the University of Karachi and a University of Pennsylvania design certificate show the craft was built formally as well as on the job."),
 "s2": paras(
   "Here is where the decision came from. This seat is not a communications leadership role; it is a field acquisition one. It works as the hands-on second to our Head of Growth, personally carrying institutional deals with provincial education departments, government bodies and donor organizations through proposals, district visits and CRM pipeline discipline, with forty to sixty percent domestic travel from an Islamabad base. It is also deliberately scoped for someone roughly four to six years into their career, an earlier altitude than a Head of Communications seat, and its weeks are measured in visits logged and proposals moved rather than in reach curves.",
   "The written application documents audience growth, brand positioning and campaign leadership at real scale, but not the specific motion this seat lives in: institutional agreements pursued and closed as the primary job, with signed partnerships as the measure. And there is a structural fact to name honestly: the compensation expectation you shared sits well above what this role carries. Sector fit was never the question here; the shape of the seat was."),
 "s3": paras(
   "Our suggestion is to hold your altitude. Head-of-function communications seats in Pakistan's education and development sector are scarce and hard to fill, and a record with platform numbers published, donor systems built and reform narratives scaled is a rare, legible credential for them. If commercial partnership work attracts you, the natural adjacency is donor and institutional advancement leadership, where fundraising narrative and relationship systems are the core of the job and your existing donor engagement record carries over directly rather than starting again at a different altitude. The 2025-26 roadmap you describe, expanding global reach through diaspora-focused campaigns, is precisely the kind of mandate advancement leadership carries, which is why we point there.",
   "Our openings live at taleemabad.com, and communications and advancement roles do open as we grow; if a matched role opens, we would welcome a fresh application from you."),
 "ps": "Teacher education reform may be the least clickable subject in the country, and you built forty eight million views around it. Making the important interesting is a career-defining craft, and yours is documented."
},
{
 "app_id": 3914, "first": "Haider", "name": "Muhammad Haider Raja", "email": "haidersatti44@gmail.com",
 "subject": "Eighteen shipped projects, and a different craft",
 "role": ROLE,
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Your application was read in full, and it documents a genuine delivery record in software, so here is an honest, specific account of what we appreciated and exactly where the decision came from.",
   "We write to every applicant this way because a decision should carry its reasoning with it. Everything below is grounded in the written application alone, and we hope it is useful in choosing what comes next."),
 "s1": paras(
   "The project list is the first thing that registers: eighteen named products carried across your roles, from an AI-powered RAG chatbot and a financial crime compliance tool to a restaurant management system, a music production platform and two English learning apps. Technical project managers usually describe process; your application shows an actual shipped portfolio, which is a more convincing kind of evidence.",
   "The progression is quick and coherent. Product owner at NASTP within months of graduating, where the application describes third-party developer relationships, user research through surveys and focus groups, and competitive analysis across the product portfolio; then project management at HA Technologies handling multiple competing deadlines; then technical project management at Octaloop with budgets, scope and schedules held against stakeholder specifications while working alongside sales from acquisition through proposal; now leading cross-functional teams at Aeyron Technologies. Backing all of it with a Masters in Project Management at Bahria while working full time, on top of Agile, Scrum and project management certifications through IBM and SkillUp, shows deliberate, continuing investment in the craft.",
   "And the final-year project tells its own story: Hopin, a carpooling app, took first position at the National Aerospace Science and Technology Park. Winning at a national-level venue with a student build is the kind of early signal that tends to repeat across a career."),
 "s2": paras(
   "Here is where the decision came from. The seat is a commercial growth role, not a delivery one: the hands-on second to our Head of Growth, personally winning partnerships with provincial education departments, government bodies and development and donor organizations, carrying pipeline targets through a CRM, with forty to sixty percent domestic travel and field acquisition as the weekly rhythm.",
   "Your craft, as the written application documents it, is getting scoped work delivered on time and on budget for clients already won. The nearest commercial edges, coordinating with sales at Octaloop and building developer relationships as a product owner, sit at the boundary of that world rather than inside it. What we could not find in the application was a chapter in which winning institutional partners or carrying a revenue target was the job, or any work in the education or development sector. Delivery discipline is not a lesser craft; it is simply a different one from what this seat spends its days doing. The role required the acquisition motion already proven, and we decided on that basis alone."),
 "s3": paras(
   "Our suggestion is to choose the fork deliberately. If delivery is the craft you want to deepen, the current arc is working: eighteen shipped projects and a masters in progress point toward senior technical program roles, and the record mostly needs outcome numbers attached, budgets held, timelines hit, client retention earned. If commercial work is the pull, the cleanest bridge from where you stand is a client-facing seat in a services firm, presales, account growth or delivery-led expansion, where fluency in what engineering teams can actually build becomes the selling advantage. Either way, pick one and let two years compound in the same direction.",
   "We post openings at taleemabad.com as they go live, across technology and commercial roles; if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "A carpooling app built as a student, judged first at a national aerospace and technology venue. Shipping something real early, and winning with it, is a habit worth protecting for a whole career."
},
{
 "app_id": 3915, "first": "Talha", "name": "Muhammad Talha Qureshi", "email": "mtalhaqureshi320@gmail.com",
 "subject": "Five chapters in three years, and what to build next",
 "role": ROLE,
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Your application was read in full, and because you are early in a career that is clearly still taking shape, we want the reasoning to be genuinely useful, so here is an honest account of what we appreciated and where the decision came from.",
   "We write to every applicant this way because a decision should carry its reasoning with it. Everything below is grounded in the written application alone."),
 "s1": paras(
   "The technical depth under the business development work stood out first. SPF, DKIM, DMARC and BIMI validation, MX and DNS checks, A/B testing and campaign QA before rollout: most early-career business developers never touch deliverability engineering, and your application treats it as routine. The same goes for the tooling range, Salesforce Marketing Cloud, HubSpot, Zoho, ConvertKit, Sendy with AWS SES, Mailchimp and Brevo, plus Apollo, Skrapp and SalesQL for prospecting data. That stack fluency is a real, checkable differentiator at this stage of a career.",
   "Second, the pipeline habits. At Kaizen Global you managed the client pipeline end to end from lead intake through onboarding, keeping records accurate at every stage, and tracked performance against monthly targets with strategy adjusted on the data. At Vizz Web Solutions you now manage accounts end to end against agreed deliverables and timelines. Those are exactly the CRM disciplines that most written records only claim, and yours describes them concretely.",
   "Third, an early leadership signal: at Dot Refl you identified, onboarded and trained new team members while directing lead generation and multi-platform campaigns, which is responsibility usually held back from someone four months into a role. Finishing a computer science degree alongside full-time commercial work adds to the picture of capacity.",
   "Even the shorter chapters add texture: a year at Heetly IT Solutions delivering consistent monthly output against targets with CRM records and documentation kept clean, and six months at Protraders coordinating campaign content across platforms with design and sales teams. The fragments show the same habits as the longer roles: targets, records, coordination."),
 "s2": paras(
   "Here is where the decision came from, and it is mostly about timing and terrain. This seat is scoped for someone roughly four to six years into a growth career, and its motion is institutional: personally winning partnerships with provincial education departments, government bodies and donor organizations in Pakistan, through field visits, proposals and long relationship cycles, with forty to sixty percent domestic travel.",
   "The written application documents roughly three years across five employers, with several chapters under a year, all of it in commercial IT services and digital outreach with remote, digital-first counterparties. What we could not find was institutional or public-sector work, in-person deal cycles, or a sustained multi-year arc at one employer where results compound and can be verified at depth. None of that is a verdict on ability; three years in, almost nobody has had time to build what this seat needs, and the window it is scoped for exists precisely because the craft takes years to accumulate. The role required both the seniority and that specific terrain, and the distance on each is what decided this."),
 "s3": paras(
   "Our suggestion is consolidation. The next two to three years matter more for their depth than their titles: one employer, one segment, and a number attached to your name, deals closed, revenue sourced, retention held, so the record shows an arc instead of a sequence. Your deliverability and CRM stack knowledge is the natural edge to build around, because teams running serious outbound revenue engines hire specifically for it and few applicants can verify it the way you can. When that arc exists, seats like this one become an argument you can win on paper.",
   "Our openings live at taleemabad.com, including earlier-career commercial roles from time to time; if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "Training new hires four months into your own role at Dot Refl stayed with us. People who lift others while still climbing are the ones teams remember."
},
]

# Safety lint: tokens forbidden by the locked rules (prompt-level, stricter than harness).
BANNED = [
    (r'\u2014', 'em dash'),
    (r'\binterview\w*\b', 'interview'),
    (r'\bconversation\w*\b', 'conversation'),
    (r'\bcall\b|\bcalls\b|\bcalled\b', 'call'),
    (r'\bmet\b', 'met'),
    (r'\bspoke\b|\bspoken\b', 'spoke'),
    (r'\bdiscussion\w*\b|\bdiscussed\b', 'discussion'),
    (r"\bI\b|\bI'm\b|\bI've\b|\bmy\b|\bme\b|\bmine\b|\bmyself\b", 'first person singular'),
    (r'\bassumed\b|\bbelieved\b|\bthought\b|\bpreferred\b|\bseemed\b|\bfelt\b|\blacked\b|\benergized\b', 'intent word'),
    (r'\bscreening\b|\bshortlist\w*\b|\bscorecard\w*\b', 'internal jargon'),
    (r'\bcase study\b', 'jargon: case study'),
    (r'strong candidate|impressive|great fit|excellent fit', 'recruiting abstraction'),
    (r'we will (reach out|be in touch|contact)|keep your name on file|hear from us', 'future promise'),
    (r'\bAli\b|\bKhan\b|\bNoah\b|\bHuma\b|\bYasin\b|\bJawad\b|\bJawwad\b|\bMujtaba\b|\bHassan\b|\bFatima\b|\bBilal\b|\bMahnoor\b|\bAyesha\b', 'interviewer name'),
]

def lint(name, text):
    plain = re.sub(r'<[^>]+>', ' ', text)
    problems = []
    for pat, label in BANNED:
        m = re.search(pat, plain)
        if m:
            i = m.start()
            problems.append(f"  [{label}] ...{plain[max(0,i-40):i+40]}...")
    if problems:
        raise SystemExit(f"LINT FAIL for {name}:\n" + "\n".join(problems))

built = []
for e in EMAILS:
    content = e["subject"] + " " + e["opening"] + e["s1"] + e["s2"] + e["s3"] + e["ps"]
    lint(e["name"], content)
    html = TEMPLATE
    html = html.split("<!DOCTYPE")[1]
    html = "<!DOCTYPE" + html  # drop the top comment block
    html = html.split("<!--\nCV REJECTION RULES")[0]  # drop trailing rules comment
    html = html.replace("[SUBJECT_LINE]", e["subject"])
    html = html.replace("[ROLE]", e["role"])
    html = html.replace("[CANDIDATE_FIRST_NAME]", e["first"])
    html = re.sub(r'<p style="margin:0 0 18px 0;[^"]*">\[OPENING_PARAGRAPH:[^\]]*\]</p>', e["opening"], html)
    html = re.sub(r'<p style="margin:0 0 18px 0;[^"]*">\[SECTION_1_CONTENT:[^\]]*\]</p>', e["s1"], html)
    html = re.sub(r'<p style="margin:0 0 18px 0;[^"]*">\[SECTION_2_CONTENT:[^\]]*\]</p>', e["s2"], html)
    html = re.sub(r'<p style="margin:0 0 18px 0;[^"]*">\[SECTION_3_CONTENT:[^\]]*\]</p>', e["s3"], html)
    html = html.replace("[PS_CONTENT: one memorable, character-affirming line tied to a specific moment.]", e["ps"])
    html = re.sub(r'<!-- \[FEEDBACK_WIDGET\][^>]*-->', '<!-- FEEDBACK_WIDGET_HERE -->', html)
    assert "[" not in re.sub(r'<!--.*?-->', '', html, flags=re.S), f"unfilled placeholder in {e['name']}"
    path = os.path.join(OUT, f"{e['app_id']}_{re.sub(r'[^a-zA-Z0-9]', '_', e['name'])}.html")
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    words = len(re.sub(r'<[^>]+>', ' ', html).split())
    built.append((e["app_id"], e["name"], path, words))
    print(f"built {e['app_id']} {e['name']}: ~{words} words -> {path}")
