# -*- coding: utf-8 -*-
"""Job 42 CV-rejection feedback emails — BATCH 02 (10 candidates, manifest batch_02.json).
Layout: templates/cv_rejection_template_locked.html (v8, LOCKED — placeholders only).
Rules: 800+ words, CV-only evidence (no fabricated interaction), no em dashes, we-voice,
role-fit framing, no intent inference, candidate-initiated reapplication, no abstractions.
Outputs: output/job42/rejection_emails/<app_id>_<name>.html
DRAFTS ONLY. Nothing here sends email.
"""
import io, os, re

TEMPLATE = open(r"c:\Agent Coco\templates\cv_rejection_template_locked.html", encoding="utf-8").read()
OUT = r"c:\Agent Coco\output\job42\rejection_emails"
os.makedirs(OUT, exist_ok=True)

P = ('<p style="margin:0 0 18px 0;text-align:justify;font-family:Georgia,serif;'
     'font-size:15px;line-height:1.8;">{}</p>')

def paras(*texts):
    return "".join(P.format(t) for t in texts)

EMAILS = [
# ---------------------------------------------------------------- 3888 Haris Zaheer
{
 "app_id": 3888, "first": "Haris", "name": "Haris Zaheer", "email": "hariszaheer001@gmail.com",
 "subject": "Partner marketing for six global brands, read closely",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Your application was read in full, and because the record it describes deserves more than a form letter, here is an honest and specific account of what stood out to us and exactly where the decision came from.",
   "We write to every applicant this way for a simple reason: a decision that affects someone's next months should carry its reasoning with it. Everything below is grounded in the written application you submitted and in nothing else, and we hope it proves useful well beyond this one process."),
 "s1": paras(
   "The current chapter at Zones is a real credential. Running partner marketing for Samsung, Google, Acer, AMD, Lenovo and Microsoft at the same time means holding six demanding brand relationships to their separate standards while keeping one coherent program running underneath them. The training programs you developed for channel partners, designed to sharpen their product knowledge and their ability to carry a value proposition, describe someone who grows revenue by making other people better at selling, and that is a mature way to think about growth.",
   "The route you took into that seat matters as much as the seat itself. As an account manager you worked outbound into the US market, administered customer relationships through the CRM, and hunted bids, creating and overseeing them through to a result. Supporting deal negotiations during critical stages and helping secure several high-value agreements, as your application puts it, is exactly the unglamorous middle of commercial work that many marketing careers never touch, and yours did.",
   "The certifications tell their own quiet story: an ESET sales specialization, Veritas data protection, a Rubrik sales credential, each earned while holding a full-time role, layered on a working toolkit of Dynamics 365, Power BI and HubSpot. That pattern shows a professional who keeps raising the technical floor underneath the commercial work rather than coasting on relationships alone.",
   "And we noted the earlier chapter guiding students toward international universities and fully funded scholarships. It is a small line on the page, but organizing seminars and building community relationships to widen what students could reach is closer to our mission than most applicants ever get. The same instinct shows in the partner fairs you organized, the co-marketing campaigns built for brand recognition and lead generation, and the market research projects you proposed and managed to sharpen strategy with actual consumer insight rather than guesswork."),
 "s2": paras(
   "Here is where the decision came from, stated as concretely as the praise above. This seat is the hands-on execution engine of our growth function, working as second to our Head of Growth inside Pakistan's education ecosystem. Its counterparties are provincial education departments, government bodies and development and donor organizations. Its rhythm involves forty to sixty percent domestic travel, and its craft is field acquisition: building institutional relationships in person, district by district, and carrying them through a disciplined CRM pipeline with your own hands.",
   "Your partnership craft was built in a different arena: remote channel and alliance marketing for global technology vendors, aimed at the US market from Islamabad. Across the written application we could not find an engagement with a Pakistani government or public-sector institution, a development-sector partner, or a field-based acquisition motion. The counseling stint sits near education, but it was individual guidance rather than institutional partnership building, and this role rests on the institutional kind. With one seat to fill, we made the narrow decision to go with evidence already proven on that exact terrain."),
 "s3": paras(
   "If institutional growth work in Pakistan genuinely draws you, the bridge is buildable and shorter than it looks. Your partner-enablement instinct, teaching a counterparty to sell, transfers directly to government and development-sector partnership work, where the job is often teaching an institution to adopt. What the application needs next is one documented engagement on that terrain: a public-sector client, a donor-funded program, a provincial pilot supported through your current platform. One verifiable chapter of that kind would change how this record reads to any hiring team in our sector, because it would connect craft we can already see to ground we need it proven on.",
   "A smaller, practical note offered in good faith: the application lists activities in far greater volume than results. The engagement rates improved, the leads generated, the deal values supported through negotiation are all named as motions without figures attached, and a record as busy as this one almost certainly produced numbers worth stating. Let the document publish them plainly; hiring teams reading quickly will reward it. In the meantime, keep the vendor-alliance work compounding; it is a rising asset in a market that is still learning what good channel marketing looks like. Our openings live at taleemabad.com, and if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "The distance from counseling students on scholarship applications in 2021 to running partner marketing for Samsung and Microsoft by 2023 is covered by very few people in two years. That gradient stayed with us."
},
# ---------------------------------------------------------------- 3889 Saifullah Saleh
{
 "app_id": 3889, "first": "Saifullah", "name": "Saifullah Saleh", "email": "saif30260@gmail.com",
 "subject": "Six years of audience growth across three markets, read closely",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Your application was read in full, and because six years of work deserve more than a template, here is an honest and specific account of what we appreciated and exactly where the decision came from.",
   "We write to every applicant this way because a decision that affects someone's next months should arrive with its reasoning attached. Everything that follows is grounded in the written application you submitted and in nothing else, and we hope it is useful to you well beyond this one process."),
 "s1": paras(
   "The first thing we noted is the span of the work: six years of digital marketing carried across the USA, the UK and Canada, three markets with different buyer habits, different platform economics and different expectations of tone, all served from Pakistan and held to international delivery standards. At StakeVille you hold that span while leading a team of up to fifteen people across content, paid advertising, social management and client support, and while serving as the primary client liaison at the same time. Growth work and client stewardship held in one pair of hands is harder than it reads.",
   "Second, the paid-acquisition craft is specific, not generic. The Digi Marketing chapter names Meta campaign structures optimized separately for reach, traffic, leads and conversions, audience targeting strategies, and reporting frameworks built to show the work, alongside coordination between marketing, sales and customer success so that acquisition did not stop at the form fill. That is funnel thinking carried all the way through.",
   "Third, the Funadiq chapter shows the same craft pointed at both international and domestic customers, with follow-up processes and funnel management treated as part of acquisition rather than an afterthought, and high-value customer relationships handled personally alongside the campaign work. Retention framed as a growth lever, not a support function, is a sign of someone who understands where revenue actually leaks and where it quietly compounds.",
   "And the education line deserves naming: the Pakistan Military Academy at Kakul, followed by two degrees in international relations completed alongside working years. Whatever else changes in a career, the sequencing there shows discipline that was trained early and kept. The same orderliness runs through the operational detail of the application, from content calendars and scheduling systems to community management and A/B testing named as standing practices rather than occasional experiments, which tells us the growth work is run as a system, not a series of improvisations."),
 "s2": paras(
   "Here is where the decision came from. This seat is the hands-on execution engine of our growth function, second to our Head of Growth, inside Pakistan's education ecosystem. Its counterparties are provincial education departments, government bodies and development and donor organizations. Its rhythm is forty to sixty percent domestic travel, and its craft is field acquisition: winning institutional relationships in person, district by district, and carrying them through a disciplined CRM pipeline.",
   "Your growth craft, and it is real craft, was built almost entirely in the digital arena: audiences grown, campaigns optimized and clients served remotely, mostly for businesses overseas. Across the written application we could not find an engagement with a Pakistani government or public-sector institution, a development or donor-sector partner, an education-sector client, or a field-based acquisition motion of the kind this seat runs on daily. The role required proof on that specific terrain, and with one seat to fill we went with evidence we could verify there."),
 "s3": paras(
   "Two suggestions, offered practically. First, aim your applications where your exact toolkit is the engine: performance-marketing and digital-growth seats, including in education companies whose growth runs on consumer acquisition rather than institutional partnerships. Pakistan's consumer edtech, e-commerce and services sectors all hire for precisely the multi-channel, funnel-disciplined craft this application documents, and in those rooms the record you already hold needs no translation.",
   "Second, let the numbers carry the application. The document names channels, markets and team sizes, but the figures a hiring team wants are mostly absent: monthly spend managed, cost per lead achieved, audience growth percentages, conversion improvements, retention rates on the accounts you have kept. Six years of campaign work certainly produced them, and the reporting frameworks the application describes mean they already exist somewhere in a dashboard; stating them plainly would move any application you send next, because verifiable figures are the shortest distance between a record and a decision in your favor. Our openings live at taleemabad.com, and if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "The arc from the Pakistan Military Academy to running Meta campaigns across three continents is not a common one. The discipline that survives that first training rarely leaves a person, and it shows in how orderly this application reads."
},
# ---------------------------------------------------------------- 3890 Muhammad Shehryar Amjad
{
 "app_id": 3890, "first": "Shehryar", "name": "Muhammad Shehryar Amjad", "email": "imshehryaramjad97@gmail.com",
 "subject": "A four-times revenue month, done twice, read closely",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Your application was read in full, and because the turnaround work it documents deserves better than a form letter, here is an honest and specific account of what we appreciated and exactly where the decision came from.",
   "We write to every applicant this way for a simple reason: a decision that affects someone's next months should carry its reasoning with it. Everything below is grounded in the written application alone, and we hope it is useful well beyond this process."),
 "s1": paras(
   "The Emergi Mentors chapter is the strongest evidence in the application. Walking into a business with chronic monthly losses, a single product, zero customer retention and no functional marketing, and delivering twenty thousand dollars in the first program launch against a previous monthly average of four to five thousand, is a turnaround completed in one cycle. Repeating the result on the second cohort, compressing into two months what had previously taken six to seven, and adding months of runway both times, is what separates a repeatable operator from a lucky quarter.",
   "We also read how the result was built, and the sequence matters: a full platform audit inside thirty days, the product architecture and user journeys rebuilt within two months, end-to-end tracking installed before scaling spend, and three to four hundred strategy consultations run personally over two months as a structured customer-discovery engine that mapped pain points and shaped the program itself. Fixing the product and the measurement before pressing the marketing pedal is the discipline most growth resumes only claim, and the full-funnel paid campaigns that followed, with acquisition costs progressively reduced through segmentation and creative iteration, confirm the sequence paid off.",
   "The earlier record shows the same pattern at home. At Med-Exam Expert you revived the national chapter from loss to a continuous profit cycle, drove roughly six million rupees domestically and seventy thousand dollars plus internationally, hired across operations, sales, marketing and design, and led the company to a Presidential Award at the ICCI Tech Expo. The Spectrum chapter adds the systems layer: automated workflows built in GHL to cut manual load, full campaign lifecycles tracked against defined performance indicators, and cross-functional teams led across content, research, graphics and video. And the breadth is real: operational and marketing leadership for firms in Sydney, London, Los Angeles, Manchester and Islamabad before turning thirty."),
 "s2": paras(
   "Here is where the decision came from, stated as plainly as the praise. This seat is the hands-on execution engine of our growth function, second to our Head of Growth, inside Pakistan's education ecosystem. Its counterparties are provincial education departments, government bodies and development and donor organizations. Its rhythm is forty to sixty percent domestic travel, and its craft is field acquisition: institutional relationships won in person, district by district, and carried through a disciplined CRM pipeline.",
   "Your growth machinery, demonstrably effective, runs on a different fuel: digital funnels, paid channels, remote consultations and product rebuilds, executed for businesses headquartered overseas. Even the education-adjacent chapter, the medical exam preparation platform, grew through advertising campaigns and digital outreach rather than institutional partnership. Across the written application we could not find an engagement with a Pakistani government or public-sector institution, a development-sector partner, or a field-based acquisition motion. The role required proven ground game on exactly that terrain, and with one seat to fill we went with evidence we could verify there."),
 "s3": paras(
   "Our honest read is that your leverage sits in early-stage digital growth leadership: businesses with a broken funnel, a live product and a short runway, where a person who can audit, rebuild and relaunch inside a quarter is the difference between survival and shutdown. The application you have today wins those rooms already; aim it there deliberately rather than broadly, and lead with the Emergi numbers, because a documented four-times revenue jump repeated across two cohorts is the rarest line on the page.",
   "If the impact sector genuinely pulls you, the missing layer is one documented public-sector or donor-funded engagement in Pakistan: a government digitization pilot, an education program supported through a development partner, anything verifiable on institutional terrain. One such chapter would connect the turnaround craft we can already see to the ground our sector hires on, and given how quickly the record shows you learning new arenas, it may be a shorter bridge for you than for most. Our openings live at taleemabad.com, and if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "Taking a business from four thousand dollar months to twenty thousand is a good quarter. Doing it again on the next cohort is a method. The second time is what stayed with us."
},
# ---------------------------------------------------------------- 3893 Wajid Ali Shah (NOTE: never "Ali" in body/subject — harness name block)
{
 "app_id": 3893, "first": "Wajid", "name": "Wajid Ali Shah", "email": "wajid.ali.shahh@gmail.com",
 "subject": "Fifty production sites under a federal mandate, read closely",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Your application was read in full, and because seven years of delivery work deserve a precise explanation rather than a template, here is an honest account of what we appreciated and exactly where the decision came from.",
   "We write to every applicant this way because a decision that affects someone's next months should carry its reasoning with it. Everything below is grounded in the written application alone, and we hope it proves useful well beyond this one process."),
 "s1": paras(
   "The AJCL chapter carries real weight. Keeping multi-site Track and Trace deployments running across more than fifty production facilities in the tobacco and cement sectors, under a nationwide mandate implemented for the Federal Board of Revenue, is public-sector delivery at a scale and sensitivity most project managers never touch in an entire career. Liaising with federal authorities and manufacturing partners at the same time, holding both sides to compliance frameworks, operational standards and SLA requirements, is a balancing act the application describes matter-of-factly, and we did not read it that way; it is difficult work done quietly.",
   "The discipline underneath it is documented too: technical assessments that found operational gaps, corrective interventions supervised to completion, engineering teams trained and coordinated across multiple sites, and a paper trail of implementation reports, maintenance logs, compliance records and site verification documentation kept structured throughout. Field documentation accuracy improving because of standardized procedures you introduced is the kind of quiet result that only shows up when someone builds the system for it.",
   "The resourcing side of the record is easy to miss and should not be. Managing manpower, technical equipment and IT assets across simultaneous sites to hit milestones efficiently, while producing analytical progress reports that kept stakeholders aligned with project charters, is operational stewardship of a high order. It pairs with a habit of building others up: engineer training programs at AJCL and capacity-building initiatives at 99 Technologies both appear in the record.",
   "And the foundation is broader than one employer. A Scrum Master chapter delivering software for local and international clients, four years coordinating academic and operational programs at a university, a Master of Science in project management, a Certified Scrum Master credential, and a portfolio spanning the FBR Digital Eye and CDA Smart Parking. The application also names exposure to public-private partnerships and donor-supported projects, which we noted with genuine interest."),
 "s2": paras(
   "Here is the honest center of the decision, and we want to be as concrete about it as we were about the strengths. Your government-facing record, and it is real, is a delivery record: mandates already won, contracts already signed, systems to be implemented, maintained and kept compliant. This seat runs the opposite motion. It is the hands-on execution engine of our growth function, second to our Head of Growth, and its daily work is originating institutional demand: opening doors at provincial education departments, government bodies and donor organizations, traveling forty to sixty percent of the time, and carrying relationships from first outreach to signed partnership through a personally managed CRM pipeline.",
   "What we could not find in the written application was evidence of that acquisition motion: agreements originated rather than executed, revenue or partnership targets carried, deals moved from cold start to signature. The role required a documented record of creating institutional relationships, not only serving them faithfully once created, and with one seat to fill we went with evidence on that specific ground."),
 "s3": paras(
   "Our suggestion is to aim where your record is already rare: implementation and program-delivery leadership in government technology, compliance systems and donor-funded programs. Very few professionals in this market can document federal-authority liaison across fifty plus industrial sites; in delivery-led organizations, and in the development sector where audit readiness and reporting protocols decide credibility, that line moves an application to the top of the pile on its own.",
   "If growth work is genuinely where you want to head, make the origination thread visible. If any past project involved shaping a bid, opening a client relationship or expanding a mandate, state it with numbers, because right now the document argues delivery from start to finish. The university years matter here too: four years inside an academic institution is education-sector grounding that many applicants to our world cannot claim, and stated in outcome terms it would strengthen the story. Our openings live at taleemabad.com, and if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "Keeping documentation clean across fifty plus facilities under a federal mandate is the kind of competence nobody applauds and everybody quietly depends on. The application shows someone who has done it anyway, year after year, and that stayed with us."
},
# ---------------------------------------------------------------- 3894 Fabiha Zafar
{
 "app_id": 3894, "first": "Fabiha", "name": "Fabiha Zafar", "email": "zafabiha@gmail.com",
 "subject": "A record moving faster than the calendar, read closely",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Your application was read in full, and because what it documents is unusual for its stage, here is an honest and specific account of what we appreciated and exactly where the decision came from.",
   "We write to every applicant this way because a decision that affects someone's next months should carry its reasoning with it. In your case especially, we want the reasoning to be visible, because it is about timing rather than talent, and that distinction matters."),
 "s1": paras(
   "The density of the record is the first thing we noted. Within roughly a year of completing a computational finance degree at NED with a 3.8 grade point average, the application shows quantitative risk work at Al Baraka Bank aligned with IFRS-9 and Basel requirements, product coordination across engineering, compliance and business teams at Mahaana Wealth with sprint planning run through Azure DevOps, and merger and acquisition workflow support at Regalis Capital in a remote, fast-paced setting. Three different professional grammars learned back to back is not a normal first year by any measure.",
   "Second, the partnership thread is genuinely relevant to our world, and we want you to know it was seen. Leading partnerships and sponsorships for the Youth Innovation Challenge under the Prime Minister's Youth Programme and the Higher Education Commission, building relationships with universities, startups and ecosystem stakeholders, and supporting programs that engaged thousands of students, is education-ecosystem work in the most literal sense. Membership of the Prime Minister's National Youth Council extends the same thread into policy rooms most early-career professionals never see.",
   "Third, the builder's streak. A healthtech startup taken through customer discovery, product strategy and a business model to selection for incubation at the National Incubation Center, alongside an automation agency serving small businesses, shows someone who creates work rather than waiting for it to be assigned. And the analytical toolkit underneath, Power BI dashboards built for risk reporting, SQL and Python listed as working instruments rather than aspirations, backlog management run through Azure DevOps, means the execution keeps up with the ambition. Taken together, the application reads like a person moving considerably faster than the calendar."),
 "s2": paras(
   "Here is where the decision came from, and we want to state it carefully because it is the rare rejection that carries no criticism inside it. This seat is scoped for a professional roughly four to six years into their career: someone who has already carried an institutional sales or partnership number through several full cycles, traveled forty to sixty percent of the time to district and provincial offices across Pakistan, and run a CRM pipeline of government and donor relationships with their own hands through wins and losses alike.",
   "The written application documents professional chapters measured in months, and the partnership work closest to our arena, real as it is, sits inside structured national programs rather than a carried commercial target. What we could not find, because at this stage it could not exist yet, is the multi-year record of institutional deal-making the role required from day one: budgets negotiated with a district officer, agreements rescued after an election changed the counterparty, a revenue figure owned across a full fiscal year. That is a statement about accumulated cycles, not about capability, and nothing in the application suggests the cycles will not come."),
 "s3": paras(
   "Our suggestion is patience applied deliberately. Choose one seat in growth, partnerships or business development, ideally in the education or development sector where your Youth Programme and Higher Education Commission threads already run, and stay long enough to own a number end to end: the outreach, the follow-ups, the stalled quarters, the closed agreements. Two to three years of that record, stacked on what this application already shows, would read very differently to any hiring team, including ours. The short early stints served their purpose as exploration; the next chapter earns more if it is long enough to show a full cycle of wins and recoveries under one roof.",
   "Keep the ecosystem relationships warm while you do it; the university, startup and policy contacts built through the Youth Innovation Challenge and the National Youth Council are an asset most people at your stage simply do not have, and they compound quietly while you build the commercial record beside them. Our openings live at taleemabad.com, and roles are added as we grow; if a matched role opens, we would welcome a fresh application from you."),
 "ps": "A healthtech startup carried into National Incubation Center selection while finishing a computational finance degree at a 3.8 average says the appetite is already there. The record just needs time to catch up to it."
},
# ---------------------------------------------------------------- 3895 Aamir Mehmood
{
 "app_id": 3895, "first": "Aamir", "name": "Aamir Mehmood", "email": "a.mehmood4875@gmail.com",
 "subject": "Twenty years of operations leadership, and the shape of this seat",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. An application carrying twenty years of work deserves a precise explanation rather than a template, so here is an honest account of what we appreciated and exactly where the decision came from.",
   "We want to say at the outset that nothing below is a verdict on the career it describes. The decision is about the fit between one specific seat and one specific record, and we have tried to keep that distinction visible in every paragraph that follows, because it is the distinction that actually matters here."),
 "s1": paras(
   "The current chapter reads like an operator at full stride. Directing full-lifecycle SaaS rollouts across enterprise clients while maintaining one hundred percent on-time milestone delivery and zero scope creep is a sentence most implementation leaders cannot write. Alongside it sit commercial responsibilities most implementation leaders never hold: managing pipelines for high-value public and private procurement bids, serving as the senior escalation point for C-suite stakeholders, and evaluating joint ventures for global market access. The adoption numbers complete the picture, with user adoption accelerated by thirty five percent through repository governance and onboarding initiatives, which is growth earned after the signature, where it is hardest.",
   "The Touchstone chapter shows the systems instinct underneath. Overhauling Salesforce and HubSpot workflows to lift reporting efficiency by a quarter, building real-time dashboards tracking pipeline health, conversion and revenue velocity, and presenting them directly to executive leadership is revenue-operations craft done properly: measurement built first, judgment applied second. Standardizing revenue processes across teams so that the improvement outlived the project is the part that reads as leadership rather than housekeeping.",
   "And the two decades behind it hold their standards at every altitude. Directing operations for more than one hundred support executives at Uber while sustaining quality scores above ninety percent across channels; structuring non-standard global pricing at Motive while improving deal velocity by twenty percent and holding the line on discounting compliance across legal, finance, product and sales; guiding enterprise accounts through onboarding at Premier to a ninety five percent satisfaction rate; and, further back, managing ten accountants and preparing IFRS financial statements before the commercial chapters began. The range from accountant to commercial director, with the rigor intact the whole way, is its own credential."),
 "s2": paras(
   "Here is where the decision came from, and it rests on two structural facts about the seat rather than on the quality of the record. First, altitude. This role is a hands-on second-in-command to our Head of Growth, scoped for someone roughly four to six years into their career, whose daily reality is personally carrying a pipeline: writing the follow-ups, sitting in district office waiting rooms, running the CRM discipline with their own hands rather than reviewing it. Your last decade has been spent at director level, leading teams and escalations. The seat would use a fraction of the scope you have carried, and we concluded that would serve neither you nor the person this role is designed to grow.",
   "Second, arena. The record was built in enterprise SaaS and outsourced services for international clients, in largely remote commercial motions run from Pakistan toward markets abroad. What we could not find in the written application was engagement with Pakistan's education sector, provincial government departments, or development and donor organizations, or the field-based acquisition rhythm of forty to sixty percent domestic travel this seat runs on daily. Both facts are about the shape of the seat we have open right now, not about capability, and we would not want the decision to read otherwise."),
 "s3": paras(
   "Our suggestion is direct: aim at the altitude you have earned. Country-level commercial or operations directorships in SaaS, enterprise services and outsourcing are seats where a procurement-bid record, revenue-operations fluency and two decades of client stewardship are entry requirements rather than overshoot. An application aimed there explains itself; one aimed at a mid-career execution seat has to argue against its own seniority, and no document should be asked to do that.",
   "One practical note in good faith: the application's strongest numbers, one hundred percent milestone delivery, ninety percent plus satisfaction and retention, thirty five percent adoption gains, sit spread across the chapters; anchoring each to its client scale and contract value, and pulling two or three of them into the opening summary, would make a document this substantial land even harder and faster. Our openings live at taleemabad.com, and roles of different scope open as we grow; if a larger-scope role opens, we would welcome a fresh application from you."),
 "ps": "Zero scope creep, sustained across enterprise rollouts, twenty years into a career. Standards that refuse to sag at that distance were the detail we kept returning to."
},
# ---------------------------------------------------------------- 3896 Arslan Ahmed
{
 "app_id": 3896, "first": "Arslan", "name": "Arslan Ahmed", "email": "arslanahmedhere@gmail.com",
 "subject": "Two hundred thousand dollars closed, and an arena question",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Your application was read in full, and because the numbers in it are real numbers, here is an honest and specific account of what we appreciated and exactly where the decision came from.",
   "We write to every applicant this way because a decision that affects someone's next months should carry its reasoning with it. Everything below is grounded in the written application alone, and we hope it is useful well beyond this one process."),
 "s1": paras(
   "The gradient is the first thing that stood out. A top-performing associate closing roughly twenty thousand dollars in a single quarter of 2024, then a manager closing two hundred thousand dollars across 2025 while running a team of two business development associates and two sales development representatives. That slope, roughly ten times the production within about a year while adding management load for the first time, does not happen by accident, and it is the kind of line that makes a reader go back to the top of the page and start again.",
   "Second, the depth under the selling. Five AWS accreditations across cloud practice, generative AI and sales, active work inside the AWS Partner Network unlocking funding programs, co-selling and Marketplace motions, and a practice built around measurable outcomes like ten to thirty percent cloud cost savings for clients. Selling technical results rather than hours is a harder craft than most commercial resumes ever attempt, and the application shows it learned properly and recently.",
   "Third, the range before cloud: a top real-estate deal worth one hundred twenty seven thousand dollars closed while managing a team of four across four years at Fair Business, venture funding of 1.6 million dollars secured for a client at TECHSHO, and a monthly target of one hundred eighty two thousand dollars held for eight consecutive months at the Bank of Punjab. Different products, different buyers, the same finishing instinct. The modern outbound stack listed alongside, from Apollo and Sales Navigator to Clay and Pipedrive, says the toolkit has kept pace with the craft, and qualification discipline like BANT named explicitly says the pipeline is managed, not merely accumulated."),
 "s2": paras(
   "Here is where the decision came from. This seat is the hands-on execution engine of our growth function, second to our Head of Growth, inside Pakistan's education ecosystem. Its counterparties are provincial education departments, government bodies and development and donor organizations across the country. Its craft is field acquisition: relationships opened and closed in person, district by district, on forty to sixty percent domestic travel, and carried through a disciplined CRM pipeline from first knock to signed partnership.",
   "Your selling motion, and it demonstrably works, is outbound and digital: prospecting through LinkedIn and email into startups, SaaS companies and mid-market enterprises, largely in overseas markets, with deals progressed remotely and closed in collaboration with technical teams. Apart from an early 2018 chapter supplying defense-sector institutions, we could not find in the written application a sustained engagement with a Pakistani government body, an education-sector client, or a development or donor organization, nor a field-based acquisition rhythm of the kind this seat lives on. What was uncertain to us, reading the written record alone, was not whether you can build and close a pipeline, the numbers settle that, but whether this specific arena is one where your machinery has been proven. The role required that proof, and with one seat to fill we went with evidence we could verify there."),
 "s3": paras(
   "Our first suggestion is to protect the ladder you are on; it is working. The cloud business development track compounds fast, the AWS partner ecosystem rewards exactly the accreditation depth you have banked, and the 2025 numbers say the next rung is close. If a move made sense purely on momentum, it would be upward inside that arena, not sideways out of it into a sector where the record would have to be rebuilt from the first rung.",
   "If public-sector work genuinely draws you, there is a path that does not require abandoning the stack: cloud providers and their partners run government and public-sector motions in Pakistan, and pursuing those accounts deliberately would build documented institutional evidence while using every accreditation you already hold. One or two such engagements, named with outcomes, would make an application like yours legible to hiring teams across our sector. Our openings live at taleemabad.com, and if a closer-fit role opens, we would welcome a fresh application from you."),
 "ps": "From twenty thousand dollar quarters to a two hundred thousand dollar year in roughly twenty four months, with a team added along the way. The slope was the story we kept rereading."
},
# ---------------------------------------------------------------- 3897 Zeeshan (THIN CV — flagged)
{
 "app_id": 3897, "first": "Zeeshan", "name": "Zeeshan", "email": "zeeshanrajpoot2848@gmail.com",
 "subject": "A craft chosen deliberately from Gojra, read closely",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Your application was read in full and with care, and because we think honest detail serves you better than a polite line, here is exactly what we saw, what we could not see, and what we would do next in your position.",
   "We write to every applicant this way because a decision that affects someone's next months should carry its reasoning with it. Yours was a shorter application than most, so we will also be honest about what that meant for how it could be read, because that is the most useful thing we can offer you."),
 "s1": paras(
   "The direction is deliberate, and that counts for something real. Enrolling in an AI-focused digital marketing program at Enablers in October 2025, from Gojra in Toba Tek Singh, and pointing the work toward remote clients rather than waiting for opportunity to arrive locally, describes someone who chose a modern, measurable craft on purpose. Most people at the start of a career drift into whatever is nearby; the application shows a direction picked and then acted on, which is harder than it sounds and rarer than it should be.",
   "The skill map you present is coherent rather than scattered. Social media strategy and growth, content creation and visual storytelling, brand engagement and community building, campaign optimization, analytics and insight: these are the correct pillars of the craft you have chosen, named in the right relationship to each other rather than as a page of unrelated buzzwords. That coherence tells us the learning underway is structured, and structured learning is what turns into a real record fastest.",
   "And naming remote collaboration as a working mode, early, is more forward-looking than it appears on the page. Marketing work in Pakistan is steadily moving toward distributed teams and international clients, and building the habits for that from the first year, rather than adapting to it a decade later, is an advantage the application already claims and can keep."),
 "s2": paras(
   "Here is where the decision came from, in two honest parts. First, the scope of the seat. This role is the hands-on execution engine of our growth function, second to our Head of Growth, scoped for someone roughly four to six years into their career, with counterparties in provincial education departments, government bodies and donor organizations, forty to sixty percent domestic travel, and a personally carried CRM pipeline. The role required a multi-year, documented record of growth work, and the distance between that requirement and where the written application stands today is structural rather than marginal.",
   "Second, and we say this to help rather than to sting: the application gave us very little to evaluate. It names skills and a training program, but no employers, no project dates, no budgets, no audiences grown, no campaign results in numbers. We make decisions only on what the written record can show, and here the record could show almost nothing yet, which is very different from showing something weak. That is entirely fixable, and fixing it is the single highest-leverage thing you can do this year."),
 "s3": paras(
   "So here is the practical path we would take in your position. From this point on, document everything. Every client the remote work serves, every page managed, every campaign run: write down the platform, the timeframe, the budget if there was one, the follower growth, the engagement rate, the result in a number. Three small projects with honest figures attached will outweigh a full page of skill words in any application you ever send, because numbers are the language hiring teams can verify, and they cannot verify a list of competencies no matter how accurate it is.",
   "Complete the Enablers program and publish the work somewhere a stranger can see it: a portfolio page, a public account you grew, a before-and-after write-up with the numbers attached. Then aim at early-career social media and marketing roles, in person or remote, where the craft gets a recorded history and a manager invested in your growth. Your language profile is an asset in that search: expert Urdu and Punjabi are exactly what brands targeting domestic audiences need, and the English will strengthen with use. The seat you applied for today sits years down that road, but the road itself is real and yours is already pointed the right way. Our openings live at taleemabad.com, and if a matched role opens, we would welcome a fresh application from you."),
 "ps": "Choosing a measurable craft from Gojra and aiming it at remote clients before anyone asked you to is a direction picked on purpose. Records can be built in a few years; direction is the rarer thing, and you already have it."
},
# ---------------------------------------------------------------- 3899 Faraz Khan (NOTE: never "Khan" in body/subject — harness name block)
{
 "app_id": 3899, "first": "Faraz", "name": "Faraz Khan", "email": "farazkhankhattak@outlook.com",
 "subject": "From eight engineers to thirty, and two structural facts",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. An application this dense with shipped work deserves a precise explanation rather than a template, so here is an honest account of what we appreciated and exactly where the decision came from.",
   "We write to every applicant this way because a decision that affects someone's next months should carry its reasoning with it. Everything below is grounded in the written application alone, and in your case the decision rests on two structural facts we want to state plainly."),
 "s1": paras(
   "The organization-building is the headline. Growing Stixor and CattleXpert from eight employees to more than thirty across Pakistan, the US and South Asia, hiring twenty plus professionals, managing appraisal cycles across two business entities, and architecting the entire delivery framework underneath them, sprint ceremonies, Azure DevOps pipelines, QA tracking, documentation standards, is building the machine and the team at the same time. Few program managers get to do both; fewer still do both well enough to write it down with this much specificity.",
   "The commercial outcomes are unusually concrete for a delivery role. Modernizing CattleXpert from a 1993 legacy platform to a rebuilt 2.0 on modern architecture, scaling the client base past thirty accounts including Simplot, a multi-billion dollar US agricultural enterprise, growing platform revenue beyond a million dollars, and building the support infrastructure alongside so the growth would hold, ties engineering leadership directly to revenue in a way most applications only gesture at.",
   "And the education thread caught our attention specifically: conceiving and launching CXUniversity with a dedicated course-creation team to accelerate client onboarding, and delivering two enterprise learning management platforms across the full development lifecycle. Add the Idera engagement, institutionalizing Agile across thirty five plus developers on two revenue-generating products, and the record shows someone who builds systems that outlast their presence.",
   "The earlier chapters carry the same signature at smaller scale: account liaison for Microsoft, Nike and Adidas at Zones with client-reported issues cut by roughly forty percent through consistent, transparent communication, a ninety two percent satisfaction score sustained across eighty plus daily claims at Ibex, outperforming the team average throughout the tenure, and a Shopify commerce platform delivered two weeks early and ten percent under budget at Lemon Tech. Wherever the application is opened, the work finishes clean."),
 "s2": paras(
   "Here are the two facts, stated without decoration because you have earned a straight answer. First, compensation: the expectation you shared sits well above what this role carries. That gap is structural to how the seat is graded, not a margin that negotiation could close, and we would rather tell you that cleanly at the start than draw you into a process that ends at an offer you could not reasonably accept.",
   "Second, the craft the seat runs on. This is a hands-on growth-execution role, second to our Head of Growth and scoped for someone roughly four to six years into their career, whose daily work is originating institutional partnerships in person: provincial education departments, government bodies and donor organizations, forty to sixty percent domestic travel, and a personally carried CRM pipeline from first outreach to signed agreement. Your record is building and shipping software and scaling the organizations that do it. What we could not find in the written application was a field acquisition motion or a government or development-sector partnership record, and the role required exactly that. Both facts describe the seat, not the professional."),
 "s3": paras(
   "Our suggestion is to keep aiming at what the record already argues for: senior technical program leadership and delivery directorships, where growing an engineering organization while holding revenue outcomes is the entry requirement rather than a bonus. The application as written wins those rooms, and the weekend degree in artificial intelligence will only widen them as more products cross that boundary.",
   "If education is what draws you to us, there is a bridge worth naming: the CXUniversity and learning-platform chapters are genuine edtech product experience, and product leadership seats in education companies would use them directly, on the build side of the house rather than the field side, where curriculum meets software and someone has to own the roadmap. That is where your application reads strongest in our sector, and it is a real market in Pakistan right now. Our openings live at taleemabad.com, and roles of different shapes open as we grow; if a matched role opens, we would welcome a fresh application from you."),
 "ps": "Modernizing a platform born in 1993 while sitting in weekend classes for a master's degree in artificial intelligence: the application holds both ends of three decades of software at once, and that range stayed with us."
},
# ---------------------------------------------------------------- 3901 Irfan Ullah (CV name Irfan Ullah Khan — never "Khan" in body/subject)
{
 "app_id": 3901, "first": "Irfan", "name": "Irfan Ullah", "email": "2pmIrfan@gmail.com",
 "subject": "Twelve years of delivery, measured against a growth seat",
 "role": "Senior Manager Growth · Taleemabad",
 "opening": paras(
   "We have completed our evaluation of your application for the Senior Manager Growth role, and we will not be moving you forward at this time. Twelve years of documented delivery work deserve a precise explanation rather than a template, so here is an honest account of what we appreciated and exactly where the decision came from.",
   "We write to every applicant this way because a decision that affects someone's next months should carry its reasoning with it. Everything below is grounded in the written application alone, and we hope it proves useful well beyond this one process."),
 "s1": paras(
   "The arc is the first thing worth naming: an Android developer in 2014, a software engineer through 2017, a project manager for five years at VSol holding a ninety five percent project success rate and a fifteen percent reduction in scope creep, and now a technical project manager directing AI, generative AI and automation portfolios for international clients. Careers that re-tool this consistently across twelve years are rare, and the certification trail, PMP, Certified Scrum Master, agile project management, alongside a working vocabulary of LLMs, retrieval systems and modern deployment stacks, shows the re-tooling was deliberate rather than drift.",
   "Second, the commercial instinct inside the delivery work. The NESL-IT chapter documents upselling opportunities identified and pursued to a forty percent revenue increase through added services, client retention and satisfaction lifted thirty seven percent by anticipating the next phase of each engagement, project and budget visibility raised ninety percent through Atlas tracking, client onboarding managed to one hundred percent satisfaction during the engagement, and losses cut by a quarter through better resource allocation. Delivery managers who move revenue numbers, not just timelines, are a small minority, and the written application places you in it with specifics rather than adjectives.",
   "Third, the product discipline: two hundred fifty plus user stories written with acceptance criteria at En Route Technologies, a product backlog held against a stated vision, a ninety eight percent quality pass rate, and timelines improved by a fifth. The current chapter extends the same discipline into newer terrain, directing concurrent AI initiatives from concept to production, spanning agents, workflow automation and enterprise solutions, while owning budgets, capacity forecasting and release management across multiple teams. The habits of someone who finishes things cleanly appear in every chapter of the record."),
 "s2": paras(
   "Here is where the decision came from, and it rests on two structural facts about the seat rather than the record. First, altitude: this seat is a hands-on second-in-command to our Head of Growth, scoped for someone roughly four to six years into their career, and its daily reality is personally carrying a pipeline through follow-ups, district visits and CRM discipline. Twelve years of directing delivery portfolios sits well above that scope, and we concluded the seat would use only a fraction of what you have carried, which serves nobody well for long.",
   "Second, the craft itself. The growth this role drives is origination: opening new institutional relationships with provincial education departments, government bodies and development and donor organizations, in person, across districts, on forty to sixty percent domestic travel. Your commercial wins, real and well documented as they are, were earned inside existing client relationships, expanding and deepening accounts already won. What we could not find in the written application was evidence of new-institution acquisition, education-sector work, or public-sector partnership building, and the role required exactly that terrain from the first week. Both facts describe the shape of the seat we have open, not the quality of the record you have built."),
 "s3": paras(
   "Our suggestion is to aim where the record already argues: senior technical program leadership in AI services, where directing generative AI portfolios for international clients is currently one of the scarcest and most sought credentials in this market. That application needs no translation anywhere it lands, and the certification trail plus the hands-on toolkit will keep it current for years to come.",
   "And consider the account-growth thread seriously: the documented upsell and retention numbers point toward client-partner and account-director seats in technology services, where commercial instinct meets delivery credibility at precisely your altitude, and where the growth motion runs through accounts you already hold rather than districts you have never visited. That is where the forty percent revenue line becomes the headline rather than a bullet, and where twelve years of finishing things cleanly is priced correctly. Our openings live at taleemabad.com, and roles of different scope open as we grow; if a larger-scope role opens, we would welcome a fresh application from you."),
 "ps": "An Android developer in 2014, a director of generative AI portfolios in 2026, with the certifications collected one by one in between. The application documents someone who never stopped re-tooling, and that stayed with us."
},
]

built = []
for e in EMAILS:
    html = TEMPLATE
    html = html.split("<!DOCTYPE")[1]
    html = "<!DOCTYPE" + html  # drop the top comment block
    html = html.split("<!--\nCV REJECTION RULES")[0]  # drop trailing rules comment
    html = html.replace("[SUBJECT_LINE]", e["subject"])
    html = html.replace("[ROLE]", e["role"])
    html = html.replace("[CANDIDATE_FIRST_NAME]", e["first"])
    html = re.sub(r'<p style="margin:0 0 18px 0;[^"]*">\[OPENING_PARAGRAPH:[^\]]*\]</p>', e["opening"], html)
    html = re.sub(r'<p style="margin:0 0 18px 0;[^"]*">\[SECTION_1_CONTENT:[^\]]*\]</p>', e["s1"], html)
    html = re.sub(r'<p style="margin:0 0 18px 0;[^"]*">\[SECTION_2_CONTENT:[^\]]*\]</p>', e["s2"], html)
    html = re.sub(r'<p style="margin:0 0 18px 0;[^"]*">\[SECTION_3_CONTENT:[^\]]*\]</p>', e["s3"], html)
    html = html.replace("[PS_CONTENT: one memorable, character-affirming line tied to a specific moment.]", e["ps"])
    html = re.sub(r'<!-- \[FEEDBACK_WIDGET\][^>]*-->', '<!-- FEEDBACK_WIDGET_HERE -->', html)
    assert "[" not in re.sub(r'<!--.*?-->', '', html, flags=re.S), f"unfilled placeholder in {e['name']}"
    path = os.path.join(OUT, f"{e['app_id']}_{re.sub(r'[^a-zA-Z0-9]', '_', e['name'])}.html")
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
    words = len(re.sub(r'<[^>]+>', ' ', html).split())
    built.append((e["app_id"], e["name"], path, words))
    print(f"built {e['app_id']} {e['name']}: ~{words} words -> {path}")
